In [1]:
import matplotlib.pyplot as plt
import tensorflow as tf
import numpy as np
import pandas as pd
%matplotlib inline

In [53]:
traindata = pd.read_csv('./DataSampling/logistic_test.csv')
train_X = np.transpose(np.array([traindata['X1'], traindata['X2']]))
train_Y = np.transpose(np.array([traindata['Y']]))

In [54]:
X = tf.placeholder('float')
Y = tf.placeholder('float')
W = tf.Variable(np.random.randn(2, 1), name='weight', dtype=tf.float32)
b = tf.Variable(np.random.randn(1), name='bias', dtype=tf.float32)

In [55]:
activation = tf.sigmoid(tf.add(tf.matmul(X, W), b))

In [56]:
cost = tf.reduce_sum(tf.pow(activation-Y, 2.))/(2*train_Y.shape[0])

In [57]:
optimizer = tf.train.GradientDescentOptimizer(0.01).minimize(cost)

In [58]:
init = tf.global_variables_initializer()

In [59]:
display_step = 50
with tf.Session() as sess:
    sess.run(init)

    # Fit all training data
    for epoch in range(1000):
        for (x, y) in zip(train_X, train_Y):
            sess.run(optimizer, feed_dict={X: x, Y: y})

        # Display logs per epoch step
        if (epoch+1) % display_step == 0:
            c = sess.run(cost, feed_dict={X: train_X, Y:train_Y})
            print("Epoch:", '%04d' % (epoch+1), "cost=", "{:.9f}".format(c), \
                "W=", sess.run(W), "b=", sess.run(b))

    print("Optimization Finished!")
    training_cost = sess.run(cost, feed_dict={X: train_X, Y: train_Y})
    print("Training cost=", training_cost, "W=", sess.run(W), "b=", sess.run(b), '\n')
    
    print sess.run(activation, feed_dict={X: train_X})

InvalidArgumentError: In[0] is not a matrix
	 [[Node: MatMul_5 = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_Placeholder_14_0, weight_7/read)]]

Caused by op u'MatMul_5', defined at:
  File "//anaconda/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "//anaconda/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "//anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 596, in launch_instance
    app.start()
  File "//anaconda/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 442, in start
    ioloop.IOLoop.instance().start()
  File "//anaconda/lib/python2.7/site-packages/zmq/eventloop/ioloop.py", line 162, in start
    super(ZMQIOLoop, self).start()
  File "//anaconda/lib/python2.7/site-packages/tornado/ioloop.py", line 883, in start
    handler_func(fd_obj, events)
  File "//anaconda/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "//anaconda/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "//anaconda/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "//anaconda/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "//anaconda/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "//anaconda/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 276, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "//anaconda/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "//anaconda/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 391, in execute_request
    user_expressions, allow_stdin)
  File "//anaconda/lib/python2.7/site-packages/ipykernel/ipkernel.py", line 199, in do_execute
    shell.run_cell(code, store_history=store_history, silent=silent)
  File "//anaconda/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2723, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "//anaconda/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2825, in run_ast_nodes
    if self.run_code(code, result):
  File "//anaconda/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2885, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-55-f4d8ea4fd456>", line 1, in <module>
    activation = tf.sigmoid(tf.add(tf.matmul(X, W), b))
  File "//anaconda/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.py", line 1801, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
  File "//anaconda/lib/python2.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 1263, in _mat_mul
    transpose_b=transpose_b, name=name)
  File "//anaconda/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "//anaconda/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "//anaconda/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): In[0] is not a matrix
	 [[Node: MatMul_5 = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_Placeholder_14_0, weight_7/read)]]


In [44]:
train_X

array([[ 0.87089506,  3.92107779],
       [-1.06033662, -0.04492077],
       [-4.87514178,  3.93222695],
       [-3.72325476,  2.33285206],
       [ 4.95402848,  1.16623081],
       [-1.63198718,  2.28896917],
       [ 2.60361803, -3.96035779],
       [-2.62411222,  4.76120042],
       [ 1.77881394, -3.07392774],
       [ 0.81800566, -4.11820929],
       [-0.40703312, -1.05175194],
       [ 0.26923086,  3.56390826],
       [-0.30254426,  4.02546516],
       [-3.46490283, -0.69926329],
       [ 4.34677446,  4.9575657 ],
       [ 1.07823401, -1.38730401],
       [-0.52462976, -4.17664381],
       [-3.42607977, -0.4834338 ],
       [-2.31960465,  0.52799634],
       [ 0.17357964,  2.18851455],
       [ 2.04265107,  0.84737818],
       [-4.53563574,  1.68896461],
       [-2.68171801, -1.53175941],
       [-4.27242652, -1.69965623],
       [-1.81289866, -0.94173962],
       [ 1.79601205,  4.71917962],
       [ 3.18858161, -0.7302627 ],
       [ 0.8046715 , -0.97539231],
       [-0.01038111,

In [45]:
train_Y

array([[0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]])

In [17]:
W_guess = np.array([[2.1], [1.4]])

In [18]:
np.dot(train_X, W_guess)

array([[  7.31838853],
       [ -2.28959598],
       [ -4.73268001],
       [ -4.5528421 ],
       [ 12.03618294],
       [ -0.22261624],
       [ -0.07690305],
       [  1.15504493],
       [ -0.56798957],
       [ -4.04768113],
       [ -2.32722226],
       [  5.55485638],
       [  5.00030827],
       [ -8.25526454],
       [ 16.06881834],
       [  0.32206581],
       [ -6.94902383],
       [ -7.87157484],
       [ -4.13197489],
       [  3.42843761],
       [  5.47589671],
       [ -7.16028459],
       [ -7.77607099],
       [-11.3516144 ],
       [ -5.12552266],
       [ 10.37847678],
       [  5.67365361],
       [  0.32426092],
       [  0.2445841 ],
       [  9.48412214],
       [ -8.85336622],
       [ -9.70437269],
       [ -3.56172589],
       [  6.08761466],
       [  2.34711015],
       [ -2.59924989],
       [ -4.40800798],
       [  0.65882495],
       [-14.95774364],
       [ -3.17972253],
       [ -5.52144843],
       [-10.07802848],
       [-14.25251056],
       [  6

In [23]:
np.dot(np.array([[2., 1.1]]), W_guess)

array([ 5.74])

In [36]:
np.transpose(np.array([train_Y]))

array([[0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]])

In [9]:
np.random.rand(2,1)

array([[ 0.89080172],
       [ 0.33760275]])

In [31]:
W.dtype

tf.float64_ref

In [37]:
b.dtype

tf.float64_ref

In [33]:
X.dtype

tf.float32

In [34]:
Y.dtype

tf.float32