In [2]:
import matplotlib.pyplot as plt
import tensorflow as tf
import numpy as np
import pandas as pd
%matplotlib inline

In [37]:
traindata = pd.read_csv('./DataSampling/logistic_test.csv')
train_X = np.transpose(np.array([traindata['X1'], traindata['X2']]))
train_Y = np.transpose(np.array([traindata['Y']]))

In [62]:
X = tf.placeholder('float')
Y = tf.placeholder('float')
W = tf.Variable(np.random.randn(1, 2), name='weight')
b = tf.Variable(np.random.randn(), name='bias')

In [63]:
activation = tf.sigmoid(tf.add(tf.matmul(X, W), b))

TypeError: Input 'b' of 'MatMul' Op has type float64 that does not match type float32 of argument 'a'.

In [51]:
cost = tf.reduce_sum(tf.pow(activation-Y, 2.))/(2*train_Y.shape[0])

In [52]:
optimizer = tf.train.GradientDescentOptimizer(0.01).minimize(cost)

In [53]:
init = tf.global_variables_initializer()

In [54]:
display_step = 50
with tf.Session() as sess:
    sess.run(init)

    # Fit all training data
    for epoch in range(1000):
        for (x, y) in zip(train_X, train_Y):
            sess.run(optimizer, feed_dict={X: x, Y: y})

        # Display logs per epoch step
        if (epoch+1) % display_step == 0:
            c = sess.run(cost, feed_dict={X: train_X, Y:train_Y})
            print("Epoch:", '%04d' % (epoch+1), "cost=", "{:.9f}".format(c), \
                "W=", sess.run(W), "b=", sess.run(b))

    print("Optimization Finished!")
    training_cost = sess.run(cost, feed_dict={X: train_X, Y: train_Y})
    print("Training cost=", training_cost, "W=", sess.run(W), "b=", sess.run(b), '\n')
    
    print sess.run(activation, feed_dict={X: train_X})

('Epoch:', '0050', 'cost=', '0.528371751', 'W=', 1.9163361, 'b=', 0.11375758)
('Epoch:', '0100', 'cost=', '0.527742147', 'W=', 1.8986278, 'b=', 0.11264034)
('Epoch:', '0150', 'cost=', '0.527092338', 'W=', 1.8806372, 'b=', 0.1115435)
('Epoch:', '0200', 'cost=', '0.526420832', 'W=', 1.8623483, 'b=', 0.11046825)
('Epoch:', '0250', 'cost=', '0.525725842', 'W=', 1.8437322, 'b=', 0.10941672)
('Epoch:', '0300', 'cost=', '0.525006711', 'W=', 1.8247973, 'b=', 0.10839039)
('Epoch:', '0350', 'cost=', '0.524261236', 'W=', 1.8055142, 'b=', 0.10739122)
('Epoch:', '0400', 'cost=', '0.523487866', 'W=', 1.7858746, 'b=', 0.10642155)
('Epoch:', '0450', 'cost=', '0.522684693', 'W=', 1.765857, 'b=', 0.10548359)
('Epoch:', '0500', 'cost=', '0.521849155', 'W=', 1.7454361, 'b=', 0.10457981)
('Epoch:', '0550', 'cost=', '0.520979404', 'W=', 1.724601, 'b=', 0.10371328)
('Epoch:', '0600', 'cost=', '0.520072162', 'W=', 1.7033169, 'b=', 0.10288697)
('Epoch:', '0650', 'cost=', '0.519124508', 'W=', 1.6815634, 'b=', 0

In [55]:
train_X

array([[ 0.87089506,  3.92107779],
       [-1.06033662, -0.04492077],
       [-4.87514178,  3.93222695],
       [-3.72325476,  2.33285206],
       [ 4.95402848,  1.16623081],
       [-1.63198718,  2.28896917],
       [ 2.60361803, -3.96035779],
       [-2.62411222,  4.76120042],
       [ 1.77881394, -3.07392774],
       [ 0.81800566, -4.11820929],
       [-0.40703312, -1.05175194],
       [ 0.26923086,  3.56390826],
       [-0.30254426,  4.02546516],
       [-3.46490283, -0.69926329],
       [ 4.34677446,  4.9575657 ],
       [ 1.07823401, -1.38730401],
       [-0.52462976, -4.17664381],
       [-3.42607977, -0.4834338 ],
       [-2.31960465,  0.52799634],
       [ 0.17357964,  2.18851455],
       [ 2.04265107,  0.84737818],
       [-4.53563574,  1.68896461],
       [-2.68171801, -1.53175941],
       [-4.27242652, -1.69965623],
       [-1.81289866, -0.94173962],
       [ 1.79601205,  4.71917962],
       [ 3.18858161, -0.7302627 ],
       [ 0.8046715 , -0.97539231],
       [-0.01038111,

In [56]:
W_guess = np.array([2.1, 1.4])

In [58]:
np.dot(train_X, W_guess)

array([  7.31838853,  -2.28959598,  -4.73268001,  -4.5528421 ,
        12.03618294,  -0.22261624,  -0.07690305,   1.15504493,
        -0.56798957,  -4.04768113,  -2.32722226,   5.55485638,
         5.00030827,  -8.25526454,  16.06881834,   0.32206581,
        -6.94902383,  -7.87157484,  -4.13197489,   3.42843761,
         5.47589671,  -7.16028459,  -7.77607099, -11.3516144 ,
        -5.12552266,  10.37847678,   5.67365361,   0.32426092,
         0.2445841 ,   9.48412214,  -8.85336622,  -9.70437269,
        -3.56172589,   6.08761466,   2.34711015,  -2.59924989,
        -4.40800798,   0.65882495, -14.95774364,  -3.17972253,
        -5.52144843, -10.07802848, -14.25251056,   6.67642038,
        13.20131915,  -1.50051347,   8.40652044,  -3.54685478,
       -13.60823236,  -2.81664096])

In [23]:
np.dot(np.array([[2., 1.1]]), W_guess)

array([ 5.74])

In [36]:
np.transpose(np.array([train_Y]))

array([[0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]])

In [61]:
np.random.rand(1,2)

array([[ 0.91365322,  0.52945239]])