In [1]:
import matplotlib.pyplot as plt
import tensorflow as tf
import numpy as np
import pandas as pd
%matplotlib inline

In [2]:
traindata = pd.read_csv('./DataSampling/logistic_test.csv')
train_X = np.matrix(np.transpose(np.array([traindata['X1'], traindata['X2']])))
train_Y = np.transpose(np.array([traindata['Y']]))

In [3]:
X = tf.placeholder('float')
Y = tf.placeholder('float')
W = tf.Variable(np.random.randn(2, 1), name='weight', dtype=tf.float32)
b = tf.Variable(np.random.randn(1), name='bias', dtype=tf.float32)

In [4]:
activation = tf.sigmoid(tf.add(tf.matmul(X, W), b))

In [5]:
cost = tf.reduce_sum(tf.pow(activation-Y, 2.))/(2*train_Y.shape[0])

In [6]:
optimizer = tf.train.GradientDescentOptimizer(0.01).minimize(cost)

In [7]:
init = tf.global_variables_initializer()

In [8]:
display_step = 50
with tf.Session() as sess:
    sess.run(init)

    # Fit all training data
    for epoch in range(1000):
        for (x, y) in zip(train_X, train_Y):
            sess.run(optimizer, feed_dict={X: x, Y: y})

        # Display logs per epoch step
        if (epoch+1) % display_step == 0:
            c = sess.run(cost, feed_dict={X: train_X, Y:train_Y})
            print("Epoch:", '%04d' % (epoch+1), "cost=", "{:.9f}".format(c), \
                "W=", sess.run(W), "b=", sess.run(b))

    print("Optimization Finished!")
    training_cost = sess.run(cost, feed_dict={X: train_X, Y: train_Y})
    print("Training cost=", training_cost, "W=", sess.run(W), "b=", sess.run(b), '\n')
    
    print sess.run(activation, feed_dict={X: train_X})

('Epoch:', '0050', 'cost=', '0.180358216', 'W=', array([[ 1.16051519],
       [ 0.10758565]], dtype=float32), 'b=', array([-0.90515041], dtype=float32))
('Epoch:', '0100', 'cost=', '0.173983112', 'W=', array([[ 1.15288806],
       [ 0.05183789]], dtype=float32), 'b=', array([-0.90043217], dtype=float32))
('Epoch:', '0150', 'cost=', '0.167574197', 'W=', array([[ 1.14363801],
       [-0.00379002]], dtype=float32), 'b=', array([-0.89540434], dtype=float32))
('Epoch:', '0200', 'cost=', '0.161144137', 'W=', array([[ 1.13278174],
       [-0.05918375]], dtype=float32), 'b=', array([-0.88996726], dtype=float32))
('Epoch:', '0250', 'cost=', '0.154703572', 'W=', array([[ 1.12033737],
       [-0.11423908]], dtype=float32), 'b=', array([-0.88403249], dtype=float32))
('Epoch:', '0300', 'cost=', '0.148265690', 'W=', array([[ 1.10634243],
       [-0.16884379]], dtype=float32), 'b=', array([-0.87753344], dtype=float32))
('Epoch:', '0350', 'cost=', '0.141848207', 'W=', array([[ 1.09081912],
       [-0.

In [44]:
train_X

array([[ 0.87089506,  3.92107779],
       [-1.06033662, -0.04492077],
       [-4.87514178,  3.93222695],
       [-3.72325476,  2.33285206],
       [ 4.95402848,  1.16623081],
       [-1.63198718,  2.28896917],
       [ 2.60361803, -3.96035779],
       [-2.62411222,  4.76120042],
       [ 1.77881394, -3.07392774],
       [ 0.81800566, -4.11820929],
       [-0.40703312, -1.05175194],
       [ 0.26923086,  3.56390826],
       [-0.30254426,  4.02546516],
       [-3.46490283, -0.69926329],
       [ 4.34677446,  4.9575657 ],
       [ 1.07823401, -1.38730401],
       [-0.52462976, -4.17664381],
       [-3.42607977, -0.4834338 ],
       [-2.31960465,  0.52799634],
       [ 0.17357964,  2.18851455],
       [ 2.04265107,  0.84737818],
       [-4.53563574,  1.68896461],
       [-2.68171801, -1.53175941],
       [-4.27242652, -1.69965623],
       [-1.81289866, -0.94173962],
       [ 1.79601205,  4.71917962],
       [ 3.18858161, -0.7302627 ],
       [ 0.8046715 , -0.97539231],
       [-0.01038111,

In [45]:
train_Y

array([[0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]])

In [17]:
W_guess = np.array([[2.1], [1.4]])

In [18]:
np.dot(train_X, W_guess)

array([[  7.31838853],
       [ -2.28959598],
       [ -4.73268001],
       [ -4.5528421 ],
       [ 12.03618294],
       [ -0.22261624],
       [ -0.07690305],
       [  1.15504493],
       [ -0.56798957],
       [ -4.04768113],
       [ -2.32722226],
       [  5.55485638],
       [  5.00030827],
       [ -8.25526454],
       [ 16.06881834],
       [  0.32206581],
       [ -6.94902383],
       [ -7.87157484],
       [ -4.13197489],
       [  3.42843761],
       [  5.47589671],
       [ -7.16028459],
       [ -7.77607099],
       [-11.3516144 ],
       [ -5.12552266],
       [ 10.37847678],
       [  5.67365361],
       [  0.32426092],
       [  0.2445841 ],
       [  9.48412214],
       [ -8.85336622],
       [ -9.70437269],
       [ -3.56172589],
       [  6.08761466],
       [  2.34711015],
       [ -2.59924989],
       [ -4.40800798],
       [  0.65882495],
       [-14.95774364],
       [ -3.17972253],
       [ -5.52144843],
       [-10.07802848],
       [-14.25251056],
       [  6

In [23]:
np.dot(np.array([[2., 1.1]]), W_guess)

array([ 5.74])

In [36]:
np.transpose(np.array([train_Y]))

array([[0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]])

In [9]:
np.random.rand(2,1)

array([[ 0.89080172],
       [ 0.33760275]])

In [31]:
W.dtype

tf.float64_ref

In [37]:
b.dtype

tf.float64_ref

In [33]:
X.dtype

tf.float32

In [34]:
Y.dtype

tf.float32