In [1]:
import numpy as np
import pandas as pd
%matplotlib inline

In [2]:
traindata = pd.read_csv('./DataSampling/logistic_test.csv')
train_X = np.transpose(np.array([traindata['X1'], traindata['X2']]))
train_Y = np.transpose(np.array([traindata['Y']]))

In [19]:
W_guess = np.random.rand(2,1)
b_guess = np.random.rand(1)

In [20]:
sigmoid = lambda g: 1./(1+np.exp(-g))

In [21]:
np.dot(train_X, W_guess) + b_guess

array([[ 1.98294787],
       [ 0.24692005],
       [ 0.0317496 ],
       [-0.01170915],
       [ 2.62198538],
       [ 0.68759151],
       [ 0.42757863],
       [ 1.0229042 ],
       [ 0.38827441],
       [-0.22266372],
       [ 0.19513362],
       [ 1.68112958],
       [ 1.61226567],
       [-0.7489325 ],
       [ 3.4471431 ],
       [ 0.60896497],
       [-0.6951962 ],
       [-0.67699795],
       [-0.02545782],
       [ 1.27433098],
       [ 1.54505828],
       [-0.46321313],
       [-0.70910672],
       [-1.29579559],
       [-0.25306629],
       [ 2.51475776],
       [ 1.50548791],
       [ 0.62801415],
       [ 0.66801142],
       [ 2.2562976 ],
       [-0.99546907],
       [-1.17506099],
       [-0.06779967],
       [ 1.73940966],
       [ 0.87030239],
       [ 0.03311481],
       [-0.05984591],
       [ 0.5296189 ],
       [-2.00465732],
       [ 0.30838652],
       [-0.27619539],
       [-1.20999287],
       [-1.87160641],
       [ 1.58803279],
       [ 2.88515588],
       [ 0

In [22]:
activation=sigmoid(np.dot(train_X, W_guess) + b_guess)

In [23]:
activation

array([[ 0.87899506],
       [ 0.56141828],
       [ 0.50793673],
       [ 0.49707274],
       [ 0.93226319],
       [ 0.66543093],
       [ 0.60529532],
       [ 0.73553792],
       [ 0.59586723],
       [ 0.44456293],
       [ 0.5486292 ],
       [ 0.84305405],
       [ 0.83372571],
       [ 0.32105395],
       [ 0.96914583],
       [ 0.64770466],
       [ 0.33287815],
       [ 0.33693166],
       [ 0.49363589],
       [ 0.78148324],
       [ 0.82419885],
       [ 0.38622386],
       [ 0.32979625],
       [ 0.21487346],
       [ 0.43706892],
       [ 0.92516994],
       [ 0.81839155],
       [ 0.65203904],
       [ 0.66105774],
       [ 0.90519237],
       [ 0.26983319],
       [ 0.23594141],
       [ 0.48305657],
       [ 0.85061207],
       [ 0.70480861],
       [ 0.50827795],
       [ 0.48504299],
       [ 0.62939422],
       [ 0.1187148 ],
       [ 0.57649138],
       [ 0.43138677],
       [ 0.22970231],
       [ 0.13335596],
       [ 0.83033915],
       [ 0.94710774],
       [ 0

In [24]:
train_Y

array([[0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]])

In [25]:
np.sum(np.power(activation-train_Y, 2.))

17.523908116048464