In [1]:
import numpy as np
import tensorflow as tf

In [2]:
X1 = tf.Variable(np.random.rand(1, 2))
X2 = tf.Variable(np.random.rand(1, 2))
D12 = tf.sqrt(tf.reduce_sum(tf.square(X1-X2)))
X = tf.Variable(np.random.rand(2, 2))

Y = tf.Variable(np.random.rand(2, 2), dtype='float')
sqY = tf.reduce_sum(Y*Y, 1)
sqY = tf.reshape(sqY, [-1, 1])
sqDY = sqY - 2*tf.matmul(Y, tf.transpose(Y)) + tf.transpose(sqY)
DY = tf.sqrt(sqDY)

In [3]:
grad_D1 = tf.gradients(D12, X1)
grad_D2 = tf.gradients(D12, X2)

In [4]:
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

In [5]:
sess.run(X1)

array([[ 0.78405005,  0.01126226]])

In [6]:
sess.run(X2)

array([[ 0.10679511,  0.20276892]])

In [7]:
sess.run(D12)

0.70381038804730567

In [8]:
sess.run(grad_D1)

[array([[ 0.96226904, -0.27209979]])]

In [9]:
sess.run(Y)

array([[ 0.96435195,  0.356516  ],
       [ 0.84333563,  0.32569844]], dtype=float32)

In [10]:
sess.run(DY)

array([[ 0.        ,  0.12487859],
       [ 0.12487882,  0.        ]], dtype=float32)

In [11]:
sess.run(tf.gradients(sqDY, Y))

[array([[ 0.48406553,  0.12327027],
        [-0.48406506, -0.12327027]], dtype=float32)]

In [12]:
sess.run(tf.gradients(sqY+tf.transpose(sqY), Y))

[array([[ 7.71481562,  2.85212803],
        [ 6.74668503,  2.60558748]], dtype=float32)]

In [15]:
sess.run(tf.gradients(sqDY, Y))

[array([[ 0.48406553,  0.12327027],
        [-0.48406506, -0.12327027]], dtype=float32)]

In [16]:
sess.run(tf.gradients(tf.sqrt(sqDY), Y))

[array([[ nan,  nan],
        [ nan,  nan]], dtype=float32)]

In [18]:
np.triu(sess.run(tf.gradients(sqDY, Y)))

array([[[ 0.48406553,  0.12327027],
        [ 0.        , -0.12327027]]], dtype=float32)

In [19]:
np.sqrt(sess.run(tf.gradients(sqDY, Y)))

/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:1: RuntimeWarning: invalid value encountered in sqrt
  if __name__ == '__main__':


array([[[ 0.69574821,  0.35109866],
        [        nan,         nan]]], dtype=float32)