In [1]:
import numpy as np
import tensorflow as tf

In [33]:
X1 = tf.Variable(np.random.rand(1, 2))
X2 = tf.Variable(np.random.rand(1, 2))
D12 = tf.sqrt(tf.reduce_sum(tf.square(X1-X2)))
X = tf.Variable(np.random.rand(2, 2))
Y = tf.reshape(tf.reduce_sum(X*X), [-1, 1])

In [3]:
grad_D1 = tf.gradients(D12, X1)
grad_D2 = tf.gradients(D12, X2)

In [34]:
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

In [26]:
sess.run(X1)

array([[ 0.99082718,  0.80823851]])

In [27]:
sess.run(X2)

array([[ 0.11014563,  0.42809234]])

In [28]:
sess.run(D12)

0.95922421212045095

In [29]:
sess.run(grad_D1)

[array([[ 0.95589411,  0.29371152]])]

In [36]:
sess.run(Y)

array([[ 1.63915939]])

In [31]:
sess.run(tf.gradients(tf.mul(X1, tf.transpose(X1)), X1))

[array([[ 3.59813136,  3.59813136]])]

In [37]:
sess.run(tf.gradients(Y+tf.matmul(X, X), X))

[array([[ 6.00934297,  8.93672268],
        [ 9.00540315,  1.85921038]])]