In [1]:
import numpy as np
import tensorflow as tf

In [2]:
Y = tf.Variable(np.random.rand(5,2), dtype='float')
sqY = tf.reduce_sum(Y*Y, 1)
sqY = tf.reshape(sqY, [-1, 1])
sqDY = sqY - 2*tf.matmul(Y, tf.transpose(Y)) + tf.transpose(sqY)
DY = tf.sqrt(sqDY)

In [3]:
cost = tf.sqrt(tf.reduce_sum(tf.square(DY)))

In [4]:
grad_cost = tf.gradients(cost, Y)

In [5]:
tmpDY1 = DY+tf.diag(tf.constant([1.,2.,3.,4.,5.]))
upper_DY = tf.matrix_band_part(tmpDY1, 0, -1)
upper_DY_nodiag = tf.matrix_band_part(tmpDY1-tf.diag(tf.diag_part(upper_DY)), 0, -1)

In [6]:
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

In [7]:
sess.run(cost)

3.1550987

In [9]:
sess.run(DY)

array([[ 0.        ,  0.10260791,  0.91455865,  0.69915289,  0.6155985 ],
       [ 0.10260791,  0.        ,  0.81551689,  0.71687466,  0.52671671],
       [ 0.91455865,  0.81551689,  0.        ,  1.06635118,  0.34522089],
       [ 0.69915289,  0.71687466,  1.06635118,  0.        ,  0.74156004],
       [ 0.6155985 ,  0.52671671,  0.34522089,  0.74155998,  0.        ]], dtype=float32)

In [10]:
sess.run(upper_DY)

array([[ 1.        ,  0.10260791,  0.91455865,  0.69915289,  0.6155985 ],
       [ 0.        ,  2.        ,  0.81551689,  0.71687466,  0.52671671],
       [ 0.        ,  0.        ,  3.        ,  1.06635118,  0.34522089],
       [ 0.        ,  0.        ,  0.        ,  4.        ,  0.74156004],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  5.        ]], dtype=float32)

In [11]:
sess.run(upper_DY_nodiag)

array([[ 0.        ,  0.10260791,  0.91455865,  0.69915289,  0.6155985 ],
       [ 0.        ,  0.        ,  0.81551689,  0.71687466,  0.52671671],
       [ 0.        ,  0.        ,  0.        ,  1.06635118,  0.34522089],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.74156004],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ]], dtype=float32)

In [18]:
sess.run(tf.gradients(sqDY, Y))

[array([[  1.50562   ,  -7.43462849],
        [  2.46969128,  -5.62301826],
        [  5.84821033,  10.33356953],
        [-11.44149113,  -2.15275002],
        [  1.61797047,   4.87682819]], dtype=float32)]