In [1]:
import numpy as np
import tensorflow as tf

In [4]:
Y = tf.Variable(np.random.rand(5,2), dtype='float')
sqY = tf.reduce_sum(Y*Y, 1)
sqY = tf.reshape(sqY, [-1, 1])
sqDY = sqY - 2*tf.matmul(Y, tf.transpose(Y)) + tf.transpose(sqY)
DY = tf.sqrt(sqDY)

In [5]:
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

In [6]:
sess.run(Y)

array([[ 0.26746532,  0.93136823],
       [ 0.27694124,  0.94629222],
       [ 0.65196913,  0.5830484 ],
       [ 0.00100045,  0.70491129],
       [ 0.74012524,  0.56017256]], dtype=float32)

In [7]:
sess.run(sqDY)

array([[  0.00000000e+00,   3.12447548e-04,   2.69169867e-01,
          1.22286290e-01,   3.61193657e-01],
       [  3.12447548e-04,   0.00000000e+00,   2.72592008e-01,
          1.34408087e-01,   3.63627791e-01],
       [  2.69169867e-01,   2.72592008e-01,   0.00000000e+00,
          4.38610822e-01,   8.29476118e-03],
       [  1.22286260e-01,   1.34408057e-01,   4.38610822e-01,
          0.00000000e+00,   5.67254782e-01],
       [  3.61193657e-01,   3.63627791e-01,   8.29476118e-03,
          5.67254782e-01,   0.00000000e+00]], dtype=float32)

In [18]:
sess.run(DY)

array([[ 0.        ,  0.01767619,  0.51881582,  0.34969458,  0.60099387],
       [ 0.01767619,  0.        ,  0.52210349,  0.36661708,  0.6030156 ],
       [ 0.51881582,  0.52210349,  0.        ,  0.66227704,  0.09107558],
       [ 0.34969452,  0.36661702,  0.66227704,  0.        ,  0.75316316],
       [ 0.60099387,  0.6030156 ,  0.09107558,  0.75316316,  0.        ]], dtype=float32)

In [16]:
sess.run(tf.gradients(tf.reshape(sqDY, [-1]), Y))

[array([[-2.40069842,  3.72419357],
        [-2.21118021,  4.02267265],
        [ 5.28937769, -3.24220324],
        [-7.7299962 , -0.80494595],
        [ 7.05249977, -3.69971943]], dtype=float32)]

In [23]:
sess.run(tf.gradients(tf.reshape(tf.reduce_sum(tf.sqrt(sqDY+tf.diag(tf.ones(5)))), [-1]), Y))

[array([[-2.60334396,  2.1845932 ],
        [-0.39532471,  5.67749786],
        [ 2.94880104, -2.5998745 ],
        [-6.95789433, -1.85961008],
        [ 7.00776291, -3.40259933]], dtype=float32)]

In [12]:
sess.run(tf.reshape(sqDY, [-1]))

array([  0.00000000e+00,   3.12447548e-04,   2.69169867e-01,
         1.22286290e-01,   3.61193657e-01,   3.12447548e-04,
         0.00000000e+00,   2.72592008e-01,   1.34408087e-01,
         3.63627791e-01,   2.69169867e-01,   2.72592008e-01,
         0.00000000e+00,   4.38610822e-01,   8.29476118e-03,
         1.22286260e-01,   1.34408057e-01,   4.38610822e-01,
         0.00000000e+00,   5.67254782e-01,   3.61193657e-01,
         3.63627791e-01,   8.29476118e-03,   5.67254782e-01,
         0.00000000e+00], dtype=float32)

In [34]:
sess.run(tf.gradients(tf.reduce_sum([sqDY[i, j] for i in range(5) for j in range(i+1, 5)]), Y))

[array([[-1.20034945,  1.86209679],
        [-1.10559034,  2.0113368 ],
        [ 2.64468861, -1.62110138],
        [-3.86499786, -0.4024725 ],
        [ 3.52624989, -1.84985971]], dtype=float32)]

In [35]:
sess.run(tf.gradients(tf.reduce_sum([tf.sqrt(sqDY[i, j]) for i in range(5) for j in range(i+1, 5)]), Y))

[array([[-1.30167198,  1.0922966 ],
        [-0.19766235,  2.83874893],
        [ 1.47440052, -1.2999382 ],
        [-3.47894692, -0.92980528],
        [ 3.50388145, -1.70129967]], dtype=float32)]

In [36]:
sess.run(tf.gradients(tf.reduce_sum([DY[i, j] for i in range(5) for j in range(i+1, 5)]), Y))

[array([[ nan,  nan],
        [ nan,  nan],
        [ nan,  nan],
        [ nan,  nan],
        [ nan,  nan]], dtype=float32)]

In [33]:
sess.run([DY[i, j] for i in range(5) for j in range(i+1, 5)])

[0.017676186,
 0.51881582,
 0.34969458,
 0.60099387,
 0.52210349,
 0.36661708,
 0.6030156,
 0.66227704,
 0.091075584,
 0.75316316]