In [1]:
import numpy as np
import tensorflow as tf

In [2]:
X = tf.placeholder('float')
Xshape = tf.shape(X)
lenX = Xshape[0]

In [3]:
sum_X = tf.reduce_sum(X)

In [4]:
# http://stackoverflow.com/questions/37009647/compute-pairwise-distance-in-a-batch-without-replicating-tensor-in-tensorflow
sqr = tf.reduce_sum(X*X, 1)
sqr = tf.reshape(sqr, [-1, 1])
D = sqr - 2*tf.matmul(X, tf.transpose(X)) + tf.transpose(sqr)

In [5]:
tetrahedron = np.array([[0., 0., 2.5],
                      [1., 0., 0.],
                      [np.cos(np.pi/3), np.sin(np.pi/3), 0.],
                      [0.5, 0.5/np.sqrt(3), np.sqrt(2./3.)]])

In [6]:
sess = tf.Session()

In [7]:
sess.run(Xshape, feed_dict={X: tetrahedron})

array([4, 3], dtype=int32)

In [8]:
sess.run(lenX, feed_dict={X: tetrahedron})

4

In [9]:
sess.run(D, feed_dict={X: tetrahedron})

array([[ 0.        ,  7.25      ,  7.25      ,  3.16751671],
       [ 7.25      ,  0.        ,  1.        ,  1.        ],
       [ 7.25      ,  1.        ,  0.        ,  1.        ],
       [ 3.16751671,  1.        ,  1.        ,  0.        ]], dtype=float32)

In [10]:
sqrtD = tf.sqrt(D)
sess.run(sqrtD, feed_dict={X: tetrahedron})

array([[ 0.        ,  2.69258237,  2.69258237,  1.77975178],
       [ 2.69258237,  0.        ,  0.99999994,  0.99999994],
       [ 2.69258237,  0.99999994,  0.        ,  0.99999994],
       [ 1.77975178,  0.99999994,  0.99999994,  0.        ]], dtype=float32)

In [12]:
sess.run(tf.square(sqrtD), feed_dict={X: tetrahedron})

array([[ 0.        ,  7.25      ,  7.25      ,  3.16751647],
       [ 7.25      ,  0.        ,  0.99999988,  0.99999988],
       [ 7.25      ,  0.99999988,  0.        ,  0.99999988],
       [ 3.16751647,  0.99999988,  0.99999988,  0.        ]], dtype=float32)

In [ ]:
sess.close()