In [1]:
import numpy as np
import tensorflow as tf

In [3]:
X1 = tf.Variable(np.random.rand(1, 2))
X2 = tf.Variable(np.random.rand(1, 2))
D12 = tf.sqrt(tf.reduce_sum(tf.square(X1-X2)))
X = tf.Variable(np.random.rand(2, 2))

Y = tf.Variable(np.random.rand(2, 2), dtype='float')
sqY = tf.reduce_sum(Y*Y, 1)
sqY = tf.reshape(sqY, [-1, 1])
sqDY = sqY - 2*tf.matmul(Y, tf.transpose(Y)) + tf.transpose(sqY)
DY = tf.sqrt(sqDY)

In [4]:
grad_D1 = tf.gradients(D12, X1)
grad_D2 = tf.gradients(D12, X2)

In [5]:
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

In [6]:
sess.run(X1)

array([[ 0.94296525,  0.2406427 ]])

In [7]:
sess.run(X2)

array([[ 0.2828407 ,  0.01377993]])

In [8]:
sess.run(D12)

0.6980194335341281

In [9]:
sess.run(grad_D1)

[array([[ 0.94571084,  0.32500925]])]

In [10]:
sess.run(Y)

array([[ 0.37386733,  0.6321885 ],
       [ 0.88230491,  0.09666222]], dtype=float32)

In [20]:
sess.run(DY)

array([[ 0.        ,  0.73844236],
       [ 0.73844236,  0.        ]], dtype=float32)

In [21]:
sess.run(tf.gradients(sqDY, Y))

[array([[-2.03375006,  2.1421051 ],
        [ 2.03375053, -2.1421051 ]], dtype=float32)]

In [15]:
sess.run(tf.gradients(sqY+tf.transpose(sqY), Y))

[array([[ 2.99093866,  5.05750799],
        [ 7.05843925,  0.77329773]], dtype=float32)]

In [16]:
sess.run(tf.gradients(sqY, Y))

[array([[ 0.74773467,  1.264377  ],
        [ 1.76460981,  0.19332443]], dtype=float32)]