In [1]:
import numpy as np

In [2]:
def construct_p_matrix(R):
    k = R.shape[0]
    P = np.zeros((k, k))
    for m in range(k):
        P[m, m] = 1. / (np.sum(np.fromiter([1. / R[m, j] for j in range(k) if j != m], dtype=np.float_)) - (k-2))
        for j in range(k):
            if j != m:
                P[m, j] = P[m, m] * (1./R[m, j] - 1)
    return P

In [7]:
R = np.array(
    [
     [0., 0.7, 0.3, 0.6, 0.55],
     [0.3, 0., 0.8, 0.1, 0.2],
     [0.7, 0.2, 0., 0.9, 0.95],
     [0.4, 0.9, 0.1, 0., 0.55],
     [0.45, 0.8, 0.05, 0.45, 0.0]
    ]
)

In [43]:
R = np.array(
    [
        [0., 0.8, 0.3],
        [0.2, 0., 0.6],
        [0.7, 0.4, 0.]
    ]
)

In [3]:
R = np.array(
    [
        [0., 0.8],
        [0.2, 0.]
    ]
)

In [8]:
construct_p_matrix(R)

array([[0.19059406, 0.08168317, 0.44471947, 0.12706271, 0.15594059],
       [0.14070352, 0.06030151, 0.01507538, 0.54271357, 0.24120603],
       [0.07663579, 0.7152674 , 0.17881685, 0.01986854, 0.00941141],
       [0.12068265, 0.00893946, 0.7240959 , 0.0804551 , 0.0658269 ],
       [0.05385557, 0.01101591, 0.8372093 , 0.05385557, 0.04406365]])

In [9]:
M = construct_p_matrix(R).T-np.identity(5)
M[0, :] = 1.
M

array([[ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ],
       [ 0.08168317, -0.93969849,  0.7152674 ,  0.00893946,  0.01101591],
       [ 0.44471947,  0.01507538, -0.82118315,  0.7240959 ,  0.8372093 ],
       [ 0.12706271,  0.54271357,  0.01986854, -0.9195449 ,  0.05385557],
       [ 0.15594059,  0.24120603,  0.00941141,  0.0658269 , -0.95593635]])

In [10]:
np.matmul(np.linalg.inv(M), np.array([1, 0, 0, 0, 0]).T)

array([0.11239561, 0.26651994, 0.33342059, 0.18598939, 0.10167447])