In [1]:
import numpy as np
from sklearn.preprocessing import OneHotEncoder

In [2]:
enc = OneHotEncoder()

In [3]:
enc.fit([[1,2,3], [4,1,2], [2,3,1], [0,0,2]])

OneHotEncoder(categorical_features='all', dtype=<type 'numpy.float64'>,
       handle_unknown='error', n_values='auto', sparse=True)

In [4]:
enc.n_values_

array([5, 4, 4])

In [5]:
enc.feature_indices_

array([ 0,  5,  9, 13])

In [6]:
enc.transform([[2,1,3]]).toarray()

array([[ 0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.]])

In [7]:
enc.transform([[0,0,1]]).toarray()

array([[ 1.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.]])

In [8]:
enc1 = OneHotEncoder()

In [9]:
enc1.fit(np.arange(10).reshape((10,1)))

OneHotEncoder(categorical_features='all', dtype=<type 'numpy.float64'>,
       handle_unknown='error', n_values='auto', sparse=True)

In [10]:
enc1.transform([[0],[2],[1],[6]]).toarray()

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.]])

In [11]:
enc1.transform([[0],[2],[1],[6],[1]]).toarray()

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])