In [1]:
import numpy as np
import pyqentangle

In [2]:
tensor = np.array([[np.sqrt(0.5), 0.0, 0.0], [0.0, np.sqrt(0.3)*1.j, 0.0], [0.0, 0.0, np.sqrt(0.2)]])

In [3]:
modes = pyqentangle.schmidt_decomposition(tensor)

In [4]:
modes

[(0.7071067811865476,
  array([1.+0.j, 0.+0.j, 0.+0.j]),
  array([1.+0.j, 0.+0.j, 0.+0.j])),
 (0.5477225575051661,
  array([0.+0.j, 0.-1.j, 0.+0.j]),
  array([-0.+0.j, -1.+0.j, -0.+0.j])),
 (0.4472135954999579,
  array([0.+0.j, 0.+0.j, 1.+0.j]),
  array([0.+0.j, 0.+0.j, 1.+0.j]))]

In [5]:
import tensornetwork as tn

In [6]:
bipartite_state_node = tn.Node(tensor)

In [8]:
u, s, vh, err = tn.split_node_full_svd(bipartite_state_node, 
                                       [bipartite_state_node[0]],
                                       [bipartite_state_node[1]])

In [10]:
u.tensor

array([[1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.-1.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j]])

In [11]:
vh.tensor

array([[ 1.+0.j,  0.+0.j,  0.+0.j],
       [-0.+0.j, -1.+0.j, -0.+0.j],
       [ 0.+0.j,  0.+0.j,  1.+0.j]])

In [12]:
s.tensor

array([[0.70710678+0.j, 0.        +0.j, 0.        +0.j],
       [0.        +0.j, 0.54772256+0.j, 0.        +0.j],
       [0.        +0.j, 0.        +0.j, 0.4472136 +0.j]])