In [1]:
import numpy as np
import pyqentangle

In [2]:
tensor = np.array([[np.sqrt(0.5), np.sqrt(0.25)*1.j], [0., np.sqrt(0.25)]])

In [3]:
modes = pyqentangle.schmidt_decomposition(tensor)

In [4]:
modes

[(0.8535533905932736,
  array([0.38268343+0.5411961j , 0.        -0.38268343j]),
  array([-0.        -0.70710678j,  0.70710678+0.j        ])),
 (0.14644660940672627,
  array([1.30656296+0.92387953j, 0.92387953+0.j        ]),
  array([0.        +0.70710678j, 0.70710678+0.j        ]))]

In [8]:
np.linalg.norm(modes[0][2])

0.9999999999999999