In [1]:
import numpy as np
import pyqentangle

In [2]:
tensor = np.array([[np.sqrt(0.5), 0.0, 0.0], [0.0, np.sqrt(0.3)*1.j, 0.0], [0.0, 0.0, np.sqrt(0.2)]])

In [3]:
modes = pyqentangle.schmidt_decomposition(tensor)

In [4]:
modes

[(0.5000000000000001,
  array([1.+0.j, 0.+0.j, 0.+0.j]),
  array([1.+0.j, 0.+0.j, 0.+0.j])),
 (0.29999999999999993,
  array([0.+0.j, 0.+1.j, 0.+0.j]),
  array([0.+0.j, 1.+0.j, 0.+0.j])),
 (0.19999999999999998,
  array([0.+0.j, 0.+0.j, 1.+0.j]),
  array([0.+0.j, 0.+0.j, 1.+0.j]))]