In [1]:
import torch
from transformers import BertTokenizer, BertModel

In [2]:
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased', do_lower_case=True)
model = BertModel.from_pretrained('bert-base-uncased', output_hidden_states=True)

In [3]:
sentences = [
    'What the heck? Anyway, I do not care!', 
    'I am a British citizen.',
    'He is the king of England.', 
    'He is the king of Python, a good machine learning engineer.',
    'He is the king of Spain.'
]

In [4]:
tokenizer.tokenize(sentences[0])

['what', 'the', 'heck', '?', 'anyway', ',', 'i', 'do', 'not', 'care', '!']

In [5]:
input_ids = []
attention_masks = []
tokenized_texts = []

for sentence in sentences:
    encoded_dict = \
        tokenizer.encode_plus(
                         sentence,
                         add_special_tokens=True,
                         trunction=True,
                         max_length=48,
                         pad_to_max_length=True,
                         return_tensors='pt')
    
    marked_text = '[CLS]' + sentence + '[SEP]'
    tokenized_texts.append(tokenizer.tokenize(marked_text))
    
    input_ids.append(encoded_dict['input_ids'])

Truncation was not explicitely activated but `max_length` is provided a specific value, please use `truncation=True` to explicitely truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.
Keyword arguments {'trunction': True} not recognized.
Truncation was not explicitely activated but `max_length` is provided a specific value, please use `truncation=True` to explicitely truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.
Keyword arguments {'trunction': True} not recognized.
Truncation was not explicitely activated but `max_length` is provided a specific value, please use `truncation=True` to explicitely truncate e

In [6]:
encoded_dict

{'input_ids': tensor([[ 101, 2002, 2003, 1996, 2332, 1997, 3577, 1012,  102,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])}

In [7]:
input_ids

[tensor([[  101,  2054,  1996, 17752,  1029,  4312,  1010,  1045,  2079,  2025,
           2729,   999,   102,     0,     0,     0,     0,     0,     0,     0,
              0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
              0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
              0,     0,     0,     0,     0,     0,     0,     0]]),
 tensor([[ 101, 1045, 2572, 1037, 2329, 6926, 1012,  102,    0,    0,    0,    0,
             0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
             0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
             0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0]]),
 tensor([[ 101, 2002, 2003, 1996, 2332, 1997, 2563, 1012,  102,    0,    0,    0,
             0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
             0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
             0,    0,    0,    0, 

In [8]:
input_ids = torch.cat(input_ids, dim=0)
input_ids

tensor([[  101,  2054,  1996, 17752,  1029,  4312,  1010,  1045,  2079,  2025,
          2729,   999,   102,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0],
        [  101,  1045,  2572,  1037,  2329,  6926,  1012,   102,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0],
        [  101,  2002,  2003,  1996,  2332,  1997,  2563,  1012,   102,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,

In [9]:
segments_id = torch.ones_like(input_ids)

In [10]:
vec1, vec2, hidden_state = model(input_ids, segments_id)

In [11]:
vec1.shape

torch.Size([5, 48, 768])

In [12]:
vec2.shape

torch.Size([5, 768])

In [13]:
for vec in hidden_state:
    print(vec.shape)

torch.Size([5, 48, 768])
torch.Size([5, 48, 768])
torch.Size([5, 48, 768])
torch.Size([5, 48, 768])
torch.Size([5, 48, 768])
torch.Size([5, 48, 768])
torch.Size([5, 48, 768])
torch.Size([5, 48, 768])
torch.Size([5, 48, 768])
torch.Size([5, 48, 768])
torch.Size([5, 48, 768])
torch.Size([5, 48, 768])
torch.Size([5, 48, 768])


In [14]:
vec1

tensor([[[-0.3138,  0.2462,  0.5285,  ..., -0.2610,  0.6147, -0.5086],
         [ 0.0167,  0.6089,  0.0182,  ...,  0.5430,  0.6684, -0.2759],
         [-0.2177,  0.0715,  0.8959,  ...,  0.4597,  1.2163, -0.7695],
         ...,
         [ 0.3888, -0.3321,  0.8575,  ..., -0.7538, -0.0445, -1.1235],
         [ 0.3560, -0.3697,  0.8404,  ..., -0.7706, -0.0429, -1.2014],
         [ 0.3845, -0.3076,  0.7683,  ..., -0.6878, -0.0829, -1.4351]],

        [[-0.5446,  0.3957,  0.4429,  ..., -0.4456,  0.5724, -0.4602],
         [ 0.0259,  0.5068, -0.4471,  ..., -0.0314,  0.8646,  0.1357],
         [ 0.1698,  0.7303, -0.1191,  ..., -0.3945,  0.9425, -0.0279],
         ...,
         [ 0.4271, -0.2452,  0.9051,  ..., -0.7676, -0.0622, -1.1299],
         [ 0.4130, -0.2979,  0.8909,  ..., -0.7893, -0.0442, -1.1998],
         [ 0.4956, -0.2175,  0.8230,  ..., -0.7031, -0.0845, -1.4285]],

        [[-0.6090,  0.2783,  0.3233,  ..., -0.2305,  0.7675, -0.3901],
         [-0.2373,  0.0380,  0.3182,  ..., -0

In [15]:
vec2

tensor([[-0.6290, -0.5717, -0.9939,  ..., -0.9069, -0.6203,  0.6406],
        [-0.5509, -0.6027, -0.9871,  ..., -0.8431, -0.6295,  0.5892],
        [-0.4425, -0.5576, -0.9889,  ..., -0.8451, -0.5804,  0.3482],
        [-0.4582, -0.5811, -0.9928,  ..., -0.8960, -0.5742,  0.2432],
        [-0.4800, -0.5522, -0.9902,  ..., -0.8678, -0.6044,  0.3598]],
       grad_fn=<TanhBackward>)

In [16]:
token_embeddings = torch.stack(hidden_state, dim=0)
token_embeddings

tensor([[[[ 1.6855e-01, -2.8577e-01, -3.2613e-01,  ..., -2.7571e-02,
            3.8253e-02,  1.6400e-01],
          [ 9.8677e-01,  4.5401e-01, -1.0180e+00,  ...,  7.5422e-01,
            2.9288e-01, -1.5443e+00],
          [-7.7901e-01,  4.7813e-01,  8.5864e-02,  ..., -2.4891e-01,
            5.0784e-01, -5.6890e-01],
          ...,
          [ 1.4135e-01, -3.9700e-01, -6.2236e-02,  ...,  8.2293e-02,
           -2.5761e-01,  2.5720e-01],
          [ 2.0530e-01, -6.2230e-01, -2.4686e-01,  ..., -1.2149e-01,
           -1.6731e-01,  2.4943e-01],
          [ 4.1845e-01, -4.7524e-01, -1.8688e-01,  ..., -1.8926e-01,
           -2.6207e-01,  1.4601e-01]],

         [[ 1.6855e-01, -2.8577e-01, -3.2613e-01,  ..., -2.7571e-02,
            3.8253e-02,  1.6400e-01],
          [-3.4022e-04,  5.3974e-01, -2.8805e-01,  ...,  7.5731e-01,
            8.9008e-01,  1.6575e-01],
          [-6.3496e-01,  1.9748e-01,  2.5116e-01,  ..., -4.0819e-02,
            1.3468e+00, -6.9357e-01],
          ...,
     

In [17]:
token_embeddings.shape

torch.Size([13, 5, 48, 768])

In [18]:
# swap dimensions: [sentence, tokens, hidden layers, features]
token_embeddings = token_embeddings.permute(1, 2, 0, 3)

In [19]:
token_embeddings.shape

torch.Size([5, 48, 13, 768])

In [20]:
processed_embeddings = token_embeddings[:, :, 9:, :]
processed_embeddings.shape

torch.Size([5, 48, 4, 768])

In [29]:
embeddings = torch.reshape(processed_embeddings, (5, 48, -1))
embeddings = embeddings.detach().numpy()
embeddings.shape

(5, 48, 3072)

In [30]:
from scipy.spatial.distance import cosine

In [31]:
cosine(embeddings[2][3], embeddings[3][3])

0.14914590120315552

In [33]:
cosine(embeddings[2][3], embeddings[4][3])

0.01848292350769043

In [25]:
embeddings

tensor([[[-0.3836, -0.2600,  0.4955,  ..., -0.2610,  0.6147, -0.5086],
         [ 0.0668,  1.4839,  0.2340,  ...,  0.5430,  0.6684, -0.2759],
         [-0.0511,  0.4364,  0.2815,  ...,  0.4597,  1.2163, -0.7695],
         ...,
         [ 0.2397, -0.5940,  1.0754,  ..., -0.7538, -0.0445, -1.1235],
         [ 0.2003, -0.6420,  0.9748,  ..., -0.7706, -0.0429, -1.2014],
         [ 0.3538, -0.4248,  0.9519,  ..., -0.6878, -0.0829, -1.4351]],

        [[-0.3597, -0.3150,  0.3647,  ..., -0.4456,  0.5724, -0.4602],
         [ 0.1983,  0.5558, -0.3408,  ..., -0.0314,  0.8646,  0.1357],
         [ 0.3919,  0.1527, -0.0829,  ..., -0.3945,  0.9425, -0.0279],
         ...,
         [ 0.3015, -0.5256,  1.0983,  ..., -0.7676, -0.0622, -1.1299],
         [ 0.2945, -0.6128,  0.9852,  ..., -0.7893, -0.0442, -1.1998],
         [ 0.5366, -0.3880,  0.9748,  ..., -0.7031, -0.0845, -1.4285]],

        [[-0.3195, -0.3453,  0.3377,  ..., -0.2305,  0.7675, -0.3901],
         [-0.0812, -0.1572,  0.5675,  ..., -0