In [8]:
import numpy as np
import torch
from torch.autograd import Variable

In [4]:
torch.cuda.is_available()

False

In [5]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [6]:
device

device(type='cpu')

In [45]:
x1 = Variable(torch.tensor([1., 2., 3., 4.]))
y1 = torch.sum(x1*x1*x1)

In [46]:
# x1.cuda()
x1.to(device)

tensor([1., 2., 3., 4.])

In [47]:
y1.to(device)

tensor(100.)

In [48]:
y1.backward(torch.FloatTensor([1., 8., 27., 64.]))

RuntimeError: Mismatch in shape: grad_output[0] has a shape of torch.Size([4]) and output[0] has a shape of torch.Size([]).

In [83]:
x2 = Variable(torch.tensor([1., 2., 3., 4.]), requires_grad=True)
y2 = torch.sum(x2*x2*x2)

In [80]:
y2

tensor(100., grad_fn=<SumBackward0>)

In [81]:
torch.autograd.grad(y2, x2)

(tensor([ 3., 12., 27., 48.]),)

In [84]:
y2.backward()

In [85]:
x2.grad

tensor([ 3., 12., 27., 48.])