In [1]:
import numpy as np
import torch
from torch.autograd import Variable

In [2]:
torch.cuda.is_available()

False

In [3]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [4]:
device

device(type='cpu')

In [5]:
x1 = Variable(torch.tensor([1., 2., 3., 4.]))
y1 = torch.sum(x1*x1*x1)

In [6]:
# x1.cuda()
x1.to(device)

tensor([1., 2., 3., 4.])

In [20]:
x1.double()

tensor([1., 2., 3., 4.], dtype=torch.float64)

In [7]:
y1.to(device)

tensor(100.)

In [8]:
y1.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [13]:
x2 = Variable(torch.tensor([1., 2., 3., 4.]), requires_grad=True)
y2 = torch.sum(x2*x2*x2)

In [14]:
y2

tensor(100., grad_fn=<SumBackward0>)

In [11]:
torch.autograd.grad(y2, x2)

(tensor([ 3., 12., 27., 48.]),)

In [15]:
y2.backward()

In [16]:
x2.grad

tensor([ 3., 12., 27., 48.])