In [1]:
import numpy as np
import pyqentangle
import tensorflow as tf

# Quantum Entanglement

In [2]:
singletstate = np.array([[0., np.sqrt(0.5)], [np.sqrt(0.5), 0.]])
singlet_schmidtmodes = pyqentangle.schmidt_decomposition(singletstate)

In [3]:
singlet_schmidtmodes

[(0.7071067811865476, array([ 0., -1.]), array([-1., -0.])),
 (0.7071067811865476, array([-1.,  0.]), array([-0., -1.]))]

In [27]:
A = np.array([singlet_schmidtmodes[0][1], singlet_schmidtmodes[1][1]])
B = np.array([singlet_schmidtmodes[0][2], singlet_schmidtmodes[1][2]])
Lambda = np.diag([singlet_schmidtmodes[0][0], singlet_schmidtmodes[1][0]])

In [28]:
np.matmul(np.matmul(A.T, Lambda), B)

array([[0.        , 0.70710678],
       [0.70710678, 0.        ]])

In [6]:
entangledstate = np.array([[np.sqrt(0.3), np.sqrt(0.3)], [np.sqrt(0.4), 0.]])
entangled_schmidtmodes = pyqentangle.schmidt_decomposition(entangledstate)

In [7]:
entangled_schmidtmodes

[(0.9276611059791171,
  array([-0.79917148, -0.60110311]),
  array([-0.8816746 , -0.47185793])),
 (0.3734231814625346,
  array([-0.60110311,  0.79917148]),
  array([ 0.47185793, -0.8816746 ]))]

In [29]:
A2 = np.array([entangled_schmidtmodes[0][1], entangled_schmidtmodes[1][1]])
B2 = np.array([entangled_schmidtmodes[0][2], entangled_schmidtmodes[1][2]])
Lambda2 = np.diag([entangled_schmidtmodes[0][0], entangled_schmidtmodes[1][0]])

In [31]:
A2

array([[-0.79917148, -0.60110311],
       [-0.60110311,  0.79917148]])

In [10]:
B2

array([[-0.8816746 , -0.47185793],
       [ 0.47185793, -0.8816746 ]])

In [30]:
np.matmul(np.matmul(A2.T, Lambda2), B2)

array([[ 5.47722558e-01,  5.47722558e-01],
       [ 6.32455532e-01, -1.41183021e-16]])

# Matrix Factorization in Recommendation Systems

In [12]:
U = tf.Variable(initial_value=tf.truncated_normal([2, 2]), name='U')
V = tf.Variable(initial_value=tf.truncated_normal([2, 2]), name='V')

M = tf.matmul(tf.transpose(U), V)

In [13]:
real_data = tf.placeholder(tf.float32, shape=(2, 2), name='real_data')

In [14]:
cost = tf.reduce_sum(tf.abs(M-real_data))

In [15]:
lr = tf.constant(.001, name='learning_rate')
global_step = tf.Variable(0, trainable=False)
learning_rate = tf.train.exponential_decay(lr, global_step, 10000, 0.96, staircase=True)
optimizer = tf.train.GradientDescentOptimizer(learning_rate)
training_step = optimizer.minimize(cost, global_step=global_step)

In [16]:
sess = tf.Session()    

In [17]:
init = tf.initialize_all_variables()
sess.run(init)

for _ in range(20000):
    sess.run(training_step, feed_dict={real_data: entangledstate})

Instructions for updating:
Use `tf.global_variables_initializer` instead.


In [18]:
retU = sess.run(U)
retU

array([[ 1.2131444 ,  0.8976804 ],
       [ 0.41055915, -0.12840651]], dtype=float32)

In [19]:
retV = sess.run(V)
retV

array([[ 0.6308235 ,  0.1319524 ],
       [-0.5250333 ,  0.93998694]], dtype=float32)

In [20]:
np.matmul(retU.T, retV)

array([[ 0.5497228 ,  0.54599756],
       [ 0.63369554, -0.00224935]], dtype=float32)

In [21]:
entangledstate

array([[0.54772256, 0.54772256],
       [0.63245553, 0.        ]])

# Tensor Decomposition

In [25]:
A1 = tf.Variable(initial_value=tf.truncated_normal([2, 2]), name='A1')
A2 = tf.Variable(initial_value=tf.truncated_normal([2, 2]), name='A2')
A3 = tf.Variable(initial_value=tf.truncated_normal([2, 2]), name='A3')

T = tf.multiply(tf.multiply(A1, A2), A3)
real_tensor_data = tf.placeholder(tf.float32, shape=(2, 2, 2), name='real_tensor_data')