In [1]:
import numpy as np
import tensorflow as tf
import tfnumpy as tfnp

In [2]:
x1 = np.array([[1, 0], [0, 1], [2, -1.4]], dtype=np.float32)
x2 = np.array([[0, -1], [1, 0], [-1.5, 0.6]], dtype=np.float32)
x = np.zeros((3, 2, 2))
x[:, :, 0] = x1
x[:, :, 1] = x2

# Using numpy first

In [3]:
a = np.random.uniform(size=x.shape[2])
b = np.random.uniform(size=x.shape[2])

In [4]:
x[:, :, 0]*a[0]+x[:, :, 1]*a[1]

array([[ 0.12312745, -0.49106612],
       [ 0.49106612,  0.12312745],
       [-0.49034429,  0.12226126]])

In [5]:
Ta = sum(x[:, :, i]*a[i] for i in range(x.shape[2]))
Ta

array([[ 0.12312745, -0.49106612],
       [ 0.49106612,  0.12312745],
       [-0.49034429,  0.12226126]])

In [6]:
Tb = sum(x[:, :, i]*b[i] for i in range(x.shape[2]))
Tb

array([[ 0.95056996, -0.86778695],
       [ 0.86778695,  0.95056996],
       [ 0.59945948, -0.81012572]])

In [7]:
eigvals_a, eigvecs_a = np.linalg.eig(np.matmul(Ta, np.conjugate(Tb.T)))

In [8]:
eigvals_b, eigvecs_b = np.linalg.eig(np.conjugate(np.transpose(np.matmul(np.conjugate(Tb.T), Ta))))

In [9]:
eigvals_a

array([3.46687766e-01+0.45558075j, 3.46687766e-01-0.45558075j,
       6.37857796e-17+0.j        ])

In [10]:
eigvals_b

array([0.34668777+0.45558075j, 0.34668777-0.45558075j])

In [11]:
# pair up eigenvalues of Ta and Tb
idx_pairs = []
tol = 1e-5

for i, eigval_a in enumerate(eigvals_a):
    for j, eigval_b in enumerate(eigvals_b):
        if abs(eigval_a - eigval_b) < tol:
            idx_pairs += [(i, j)]
            break

idx_pairs

[(0, 0), (1, 1)]

In [12]:
eigvecs_a

array([[-0.74352126+0.j        , -0.74352126-0.j        ,
        -0.60495026+0.j        ],
       [ 0.02405193+0.43689028j,  0.02405193-0.43689028j,
         0.11876059+0.j        ],
       [ 0.32812439-0.38478425j,  0.32812439+0.38478425j,
         0.78735704+0.j        ]])

In [13]:
eigvecs_b

array([[0.8516954 +0.j        , 0.8516954 -0.j        ],
       [0.10961048+0.51244559j, 0.10961048-0.51244559j]])