In [1]:
import numpy as np
import tensorflow as tf
from itertools import product
import random
#import tfnumpy as tfnp

In [62]:
x1 = np.array([[-1.3, 1], [2, -1.4]], dtype=np.float32)
x2 = np.array([[1, 0], [-1.5, 0.6]], dtype=np.float32)
x = np.zeros((2, 2, 2))
x[:, :, 0] = x1
x[:, :, 1] = x2

# Using numpy first

In [63]:
a = np.random.uniform(size=x.shape[2])
b = np.random.uniform(size=x.shape[2])

In [64]:
x[:, :, 0]*a[0]+x[:, :, 1]*a[1]

array([[-0.42662046,  0.43854062],
       [ 0.66185775, -0.52786746]])

In [65]:
Ta = sum(x[:, :, i]*a[i] for i in range(x.shape[2]))
Ta

array([[-0.42662046,  0.43854062],
       [ 0.66185775, -0.52786746]])

In [66]:
Tb = sum(x[:, :, i]*b[i] for i in range(x.shape[2]))
Tb

array([[-0.55736387,  0.95288707],
       [ 0.88369023, -0.92520829]])

In [67]:
eigvals_u, eigvecs_u = np.linalg.eig(np.matmul(Ta, np.linalg.pinv(Tb)))

In [68]:
eigvals_v, eigvecs_v = np.linalg.eig(np.transpose(np.matmul(np.linalg.pinv(Ta), Tb)))

In [69]:
eigvecs_u

array([[-0.86234809,  0.54638519],
       [ 0.50631588, -0.83753401]])

In [70]:
eigvecs_v

array([[-0.83565583, -0.05469079],
       [ 0.54925344, -0.99850334]])

In [71]:
# pair up eigenvalues of Ta and Tb
idx_pairs = []
tol = 1e-5

for i, eigval_u in enumerate(eigvals_u):
    for j, eigval_v in enumerate(eigvals_v):
        if abs(eigval_u - 1/eigval_v) < tol:
            idx_pairs += [(i, j)]
            break

idx_pairs

[(0, 1), (1, 0)]

In [72]:
nbcomp = len(idx_pairs)
A = np.zeros((nbcomp*x.shape[2], nbcomp*x.shape[2]))
B = np.zeros(nbcomp*x.shape[2])
eqidx = 0
for k in range(x.shape[2]):
    for i, j in random.choices(list(product(range(x.shape[0]), range(x.shape[1]))), k=nbcomp):
        #print("{} {} {}".format(i, j, k))
        B[eqidx] = x[i, j, k]
        for ck in range(nbcomp):
            A[eqidx, ck*x.shape[2]+k] = eigvecs_u[i, idx_pairs[ck][0]]*eigvecs_v[j, idx_pairs[ck][1]]
        eqidx += 1

In [73]:
A

array([[ 0.0471625 ,  0.        , -0.45658997,  0.        ],
       [-0.02769082,  0.        ,  0.69989018,  0.        ],
       [ 0.        , -0.50555809,  0.        , -0.46001843],
       [ 0.        , -0.02769082,  0.        ,  0.69989018]])

In [74]:
B

array([-1.29999995,  2.        ,  0.60000002, -1.5       ])

In [75]:
sol = np.linalg.solve(A, B)
sol

array([ 0.16315794,  0.73680606,  2.86404645, -2.11404201])

In [76]:
eigvecs_w = sol.reshape((nbcomp, x.shape[2]), order='F')
eigvecs_w

array([[ 0.16315794,  2.86404645],
       [ 0.73680606, -2.11404201]])

In [77]:
# verfication
xh = np.zeros(x.shape)
for i, j, k in product(range(x.shape[0]), range(x.shape[1]), range(x.shape[2])):
    xh[i, j, k] = sum([eigvecs_u[i, alpha]*eigvecs_v[j, alpha]*eigvecs_w[k, alpha] for alpha in range(nbcomp)])

In [78]:
xh

array([[[ 0.03199177,  0.59413407],
        [-1.63980987,  0.80436603]],

       [[ 0.06215571, -0.40858147],
        [ 2.44051974, -1.5630295 ]]])

In [79]:
x

array([[[-1.29999995,  1.        ],
        [ 1.        ,  0.        ]],

       [[ 2.        , -1.5       ],
        [-1.39999998,  0.60000002]]])

In [32]:
eigvecs_u

array([[ 0.94285023, -0.36551167],
       [-0.33321681,  0.93080676]])

In [33]:
eigvecs_v

array([[ 0.88601964,  0.86754559],
       [-0.46364771,  0.49735766]])

In [34]:
eigvecs_w

array([[ 1.11486538,  2.81587164],
       [ 0.58340104, -1.614319  ]])