In [1]:
import numpy as np

In [2]:
mu = np.array([2.1,-1.5])
sigma = np.array([[5.7, 0.7], [0.7, 8.6]])

In [3]:
v, e = np.linalg.eig(sigma)

In [4]:
xt0 = np.random.normal(0.0, v[0], size=1000)
xt1 = np.random.normal(0.0, v[1], size=1000)

In [5]:
X = np.matmul(e, np.array([xt0, xt1]))

In [6]:
X

array([[  5.79989848,  -3.72730258, -14.38935201, ...,  -0.49196157,
          1.21740085,   5.4385806 ],
       [ -3.31483374,  -3.10112237,  -4.4272495 , ...,   6.16014984,
         -2.77868385,   1.2251711 ]])

In [7]:
X[0,:] += mu[0]
X[1,:] += mu[1]

In [8]:
X

array([[  7.89989848,  -1.62730258, -12.28935201, ...,   1.60803843,
          3.31740085,   7.5385806 ],
       [ -4.81483374,  -4.60112237,  -5.9272495 , ...,   4.66014984,
         -4.27868385,  -0.2748289 ]])

In [3]:
def check_symmetric(a, tol=1e-8):
    return np.allclose(a, a.T, atol=tol)

In [16]:
def multivar_norm_pdf(X, mu, sigma):
    n = len(mu)
    assert len(X)==n
    assert np.shape(sigma)==(n, n)
    assert check_symmetric(sigma)
    
    inv_sigma = np.linalg.inv(sigma)
    
    exponent = np.matmul(np.matmul((X-mu).reshape(1,2), inv_sigma), (X-mu).reshape(2,1))
    
    sigma_eigvals = np.linalg.eigvals(sigma)
    
    return np.sqrt(np.sum(np.prod(sigma_eigvals))/(2*np.pi)**n) * np.exp(-exponent)

In [20]:
multivar_norm_pdf(np.array([2.5, -1.0]), mu, sigma)

array([[1.05260365]])

In [13]:
np.mat

(2, 2)