In [1]:
import numpy as np

In [2]:
mu = np.array([2.1,-1.5])
sigma = np.array([[5.7, 0.7], [0.7, 8.6]])

In [3]:
def check_symmetric(a, tol=1e-8):
    return np.allclose(a, a.T, atol=tol)

In [18]:
def exponent_multiva_norm(X, mu, inv_sigma):
    n = len(mu)
    assert X.shape[1] == n
    m = X.shape[0]


    return np.sum(np.matmul((X-mu).reshape(m, n), inv_sigma)*(X-mu).reshape(m, n), axis=1)

def multivar_norm_pdf(X, mu, sigma):
    n = len(mu)
        assert np.shape(sigma) == (n, n)
    assert check_symmetric(sigma)

    inv_sigma = np.linalg.inv(sigma)
    exponent = exponent_multiva_norm(X, mu, sigma)

    sigma_eigvals = np.linalg.eigvals(sigma)
    
    return np.sqrt(np.sum(np.prod(sigma_eigvals))/(2*np.pi)**n) * np.exp(-exponent)

In [21]:
multivar_norm_pdf(np.array([[3,4],[1,-1],[3,-1]]), mu, sigma)

array([[0.75168932, 0.4035896 , 0.88239191],
       [1.28126286, 3.15146306, 0.85518299],
       [0.94487023, 0.46048289, 1.28126286]])

In [23]:
exponent_multivar_norm(np.array([[3,4],[1,-1],[3,-1]]), mu, sigma)

array([[ 0.3886462 ,  1.01057078,  0.22833299],
       [-0.14463219, -1.04465279,  0.25965382],
       [ 0.1599217 ,  0.87869359, -0.14463219]])

In [25]:
exponent_multivar_norm(np.array([[3,4]]), mu, sigma)

array([[3.55369874]])

In [32]:
np.sum(np.array([[1,2],[3,4]])*np.array([[2,3],[4,5]]), axis=1)

array([ 8, 32])

In [29]:
np.array([[1,2],[3,4]])*np.array([[2,3],[4,5]])

array([[ 2,  6],
       [12, 20]])