In [1]:
import numpy as np
from mogu.topology import SimplicialComplex, AlphaComplex

In [2]:
# ring
ring1d_sc = [(i, i+1) for i in range(10)] + [(10,0)]
# cylinder with hole
cylinder_sc = [(0, 1, 2), (1, 2, 3), (2, 3, 0), (3, 0, 1)]
# torus (https://page.mi.fu-berlin.de/rote/Papers/pdf/Computational+topology:+an+introduction.pdf)
torus_sc = [(1,2,4), (4,2,5), (2,3,5), (3,5,6), (5,6,1), (1,6,2), (6,7,2), (7,3,2),
            (1,3,4), (3,4,6), (4,6,7), (4,5,7), (5,7,1), (7,3,1)]
# sphere
sphere_sc = [(1,5,6), (5,6,2), (1,6,3), (3,6,2), (3,4,2), (1,4,5), (4,5,2)]

In [3]:
ring_c = SimplicialComplex(simplices=ring1d_sc)
print(ring_c.betti_number(0))
print(ring_c.betti_number(1))
print(ring_c.betti_number(2))

1
1
0


In [4]:
cylinder_c = SimplicialComplex(simplices=cylinder_sc)
print(cylinder_c.betti_number(0))
print(cylinder_c.betti_number(1))
print(cylinder_c.betti_number(2))

1
0
1


In [5]:
torus_c = SimplicialComplex(simplices=torus_sc)
print(torus_c.betti_number(0))
print(torus_c.betti_number(1))
print(torus_c.betti_number(2))

1
2
1


In [6]:
sphere_c = SimplicialComplex(simplices=sphere_sc)
print(sphere_c.betti_number(0))
print(sphere_c.betti_number(1))
print(sphere_c.betti_number(2))

1
0
0


In [33]:
sphere_c.boundary_operator(0).toarray()

array([[ 1.,  1.,  1.,  1.,  1.,  1.]])

In [34]:
sphere_c.boundary_operator(1).toarray()

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  1.,  0.,  1.,  1.],
       [-1.,  0., -1.,  0., -1.,  0.,  0.,  0., -1.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0., -1.,  0.,  0.,  0.,  1., -1.,  0.],
       [ 0., -1.,  0.,  1.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0., -1.,  0.,  0., -1.,  0.,  0., -1.,  0., -1.],
       [ 0.,  1.,  1.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,  0.,  0.]])

In [35]:
sphere_c.boundary_operator(2).toarray()

array([[ 0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0., -1., -1.,  0.],
       [ 0.,  0., -1.,  1.,  0.,  0.,  0.],
       [-1.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  1.,  0.],
       [ 0., -1.,  0., -1.,  0.,  0.,  0.],
       [ 1.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  1.,  0.,  0.,  0., -1.]])

In [7]:
eg1_c = SimplicialComplex(simplices=[(0, 1, 2), (1, 2, 3)])
print(eg1_c.betti_number(0))
print(eg1_c.betti_number(1))
print(eg1_c.betti_number(2))

1
0
0


In [8]:
eg2_c = SimplicialComplex(simplices=[(0,1), (1,2), (2,3), (1,3), (0,2), (0,3)])
print(eg2_c.betti_number(0))
print(eg2_c.betti_number(1))
print(eg2_c.betti_number(2))

1
3
0


In [13]:
eg1_c.boundary_operator(0).toarray()

array([[ 1.,  1.,  1.,  1.]])

In [14]:
eg1_c.boundary_operator(1).toarray()

array([[-1.,  0.,  0.,  0., -1.],
       [ 1., -1., -1.,  0.,  0.],
       [ 0.,  1.,  0., -1.,  1.],
       [ 0.,  0.,  1.,  1.,  0.]])

In [15]:
eg1_c.boundary_operator(2).toarray()

array([[ 1.,  0.],
       [ 1.,  1.],
       [ 0., -1.],
       [ 0.,  1.],
       [-1.,  0.]])

In [16]:
eg1_c.boundary_operator(3).toarray()

array([], shape=(2, 0), dtype=float64)

In [17]:
np.linalg.matrix_rank(eg1_c.boundary_operator(2).toarray())

2

In [21]:
eg1_c.boundary_operator(3).shape[1]

0

In [22]:
eg3_c = SimplicialComplex(simplices=[(1,2,3), (2,4), (3,4), (5,)])

In [24]:
eg3_c.boundary_operator(3).toarray()

array([], shape=(1, 0), dtype=float64)

In [25]:
eg3_c.boundary_operator(2).toarray()

array([[ 1.],
       [-1.],
       [ 1.],
       [ 0.],
       [ 0.]])

In [26]:
eg3_c.boundary_operator(1).toarray()

array([[-1., -1.,  0.,  0.,  0.],
       [ 1.,  0., -1.,  0., -1.],
       [ 0.,  1.,  1., -1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  1.]])

In [27]:
eg3_c.boundary_operator(0).toarray()

array([[ 1.,  1.,  1.,  1.,  1.]])

In [29]:
np.linalg.matrix_rank(eg3_c.boundary_operator(2).toarray())

1

In [30]:
np.linalg.matrix_rank(eg3_c.boundary_operator(1).toarray())

3

In [31]:
np.linalg.matrix_rank(eg3_c.boundary_operator(0).toarray())

1

In [32]:
print(eg3_c.betti_number(0))
print(eg3_c.betti_number(1))
print(eg3_c.betti_number(2))

2
1
0


In [36]:
twosphere_c = SimplicialComplex(simplices=[(1,3,4), (1,2,3), (2,3,4), (1,2,4)])

In [37]:
print(twosphere_c.betti_number(0))
print(twosphere_c.betti_number(1))
print(twosphere_c.betti_number(2))

1
0
1


In [38]:
twosphere_c.boundary_operator(1).toarray()

array([[-1., -1., -1.,  0.,  0.,  0.],
       [ 1.,  0.,  0., -1.,  0., -1.],
       [ 0.,  1.,  0.,  1., -1.,  0.],
       [ 0.,  0.,  1.,  0.,  1.,  1.]])

In [39]:
twosphere_c.boundary_operator(2).toarray()

array([[ 1.,  0.,  0.,  1.],
       [ 0.,  1.,  0., -1.],
       [-1., -1.,  0.,  0.],
       [ 0.,  0.,  1.,  1.],
       [ 0.,  1.,  1.,  0.],
       [ 1.,  0., -1.,  0.]])

In [40]:
np.linalg.matrix_rank(twosphere_c.boundary_operator(2).toarray())

3

In [41]:
np.linalg.matrix_rank(twosphere_c.boundary_operator(1).toarray())

3

In [43]:
twosphere_c.boundary_operator(3).toarray()

array([], shape=(4, 0), dtype=float64)

In [44]:
np.linalg.matrix_rank(twosphere_c.boundary_operator(0).toarray())

1

In [46]:
twosphere_c.boundary_operator(2).shape[1]-np.linalg.matrix_rank(twosphere_c.boundary_operator(2).toarray())-0

1