In [1]:
import numpy as np
import tensornetwork as tn

In [4]:
# Create the nodes
a = tn.Node(np.ones((10,))) 
b = tn.Node(np.ones((10,)))
edge = a[0] ^ b[0] # Equal to tn.connect(a[0], b[0])
final_node = tn.contract(edge)
print(final_node.tensor) # Should print 10.0

10.0


In [3]:
type(b)

tensornetwork.network_components.Node

In [4]:
type(b.tensor)

numpy.ndarray

In [20]:
edge = a[0] ^ b[0] # Equal to tn.connect(a[0], b[0])

In [12]:
tn.get_shared_edges(a, b)

{<tensornetwork.network_components.Edge at 0x11921e128>}

In [17]:
c = tn.contract_between(a, b)

In [19]:
c.tensor

array(10.)

In [21]:
c = a @ b

In [22]:
c.tensor

array(10.)

# Node Splitting and SVD

In [24]:
entangled_state = tn.Node(np.array([[0., 1.], [1., 0.]])/np.sqrt(2))

In [29]:
left_node, right_node, trunc_err = tn.split_node(entangled_state, [entangled_state[0]], [entangled_state[1]])

In [31]:
left_node.tensor

array([[ 0.        , -0.84089642],
       [-0.84089642,  0.        ]])

In [32]:
right_node.tensor

array([[-0.84089642, -0.        ],
       [-0.        , -0.84089642]])

In [34]:
u, s, vh, trunc_err = tn.split_node_full_svd(entangled_state, [entangled_state[0]], [entangled_state[1]])

In [36]:
u.tensor

array([[ 0., -1.],
       [-1.,  0.]])

In [38]:
s.tensor

array([[0.70710678, 0.        ],
       [0.        , 0.70710678]])

In [40]:
vh.tensor

array([[-1., -0.],
       [-0., -1.]])