In [1]:
import numpy as np
import tensornetwork as tn

In [6]:
import pyqentangle

In [2]:
singlet = np.array([[0., np.sqrt(0.6) * 1j], [np.sqrt(0.4) * 1j, 0.]])

# Density Matrix

In [3]:
singlet_ketnode = tn.Node(singlet)
singlet_branode = tn.Node(np.conj(singlet))

In [4]:
final_node = tn.outer_product(singlet_ketnode, singlet_branode)

In [5]:
final_node.tensor

array([[[[0.        +0.j, 0.        +0.j],
         [0.        +0.j, 0.        +0.j]],

        [[0.        +0.j, 0.6       +0.j],
         [0.48989795+0.j, 0.        +0.j]]],


       [[[0.        +0.j, 0.48989795+0.j],
         [0.4       +0.j, 0.        +0.j]],

        [[0.        +0.j, 0.        +0.j],
         [0.        +0.j, 0.        +0.j]]]])

In [7]:
pyqentangle.bipartite_denmat.bipartitepurestate_densitymatrix_cython(singlet)

array([[[[0.        +0.j, 0.        +0.j],
         [0.        +0.j, 0.        +0.j]],

        [[0.        +0.j, 0.6       +0.j],
         [0.48989795+0.j, 0.        +0.j]]],


       [[[0.        +0.j, 0.48989795+0.j],
         [0.4       +0.j, 0.        +0.j]],

        [[0.        +0.j, 0.        +0.j],
         [0.        +0.j, 0.        +0.j]]]])

# Reduced Density Matrix

In [18]:
kept= 0

In [19]:
_ = singlet_ketnode[1-kept] ^ singlet_branode[1-kept]
reddenmat = singlet_ketnode @ singlet_branode

In [20]:
reddenmat.tensor

array([[0.6+0.j, 0. +0.j],
       [0. +0.j, 0.4+0.j]])

In [21]:
pyqentangle.bipartite_reddenmat_nocheck.bipartitepurestate_reduceddensitymatrix_nocheck(singlet, kept)

array([[0.6+0.j, 0. +0.j],
       [0. +0.j, 0.4+0.j]])