In [1]:
import numpy as np
import tensornetwork as tn

In [2]:
import pyqentangle

In [3]:
singlet = np.array([[0., np.sqrt(0.6) * 1j], [np.sqrt(0.4) * 1j, 0.]])

# Density Matrix

In [4]:
singlet_ketnode = tn.Node(singlet)
singlet_branode = tn.Node(np.conj(singlet))

In [5]:
final_node = tn.outer_product(singlet_ketnode, singlet_branode)

In [6]:
final_node.tensor

array([[[[0.        +0.j, 0.        +0.j],
         [0.        +0.j, 0.        +0.j]],

        [[0.        +0.j, 0.6       +0.j],
         [0.48989795+0.j, 0.        +0.j]]],


       [[[0.        +0.j, 0.48989795+0.j],
         [0.4       +0.j, 0.        +0.j]],

        [[0.        +0.j, 0.        +0.j],
         [0.        +0.j, 0.        +0.j]]]])

In [7]:
pyqentangle.bipartite_denmat.bipartitepurestate_densitymatrix_cython(singlet)

array([[[[0.        +0.j, 0.        +0.j],
         [0.        +0.j, 0.        +0.j]],

        [[0.        +0.j, 0.6       +0.j],
         [0.48989795+0.j, 0.        +0.j]]],


       [[[0.        +0.j, 0.48989795+0.j],
         [0.4       +0.j, 0.        +0.j]],

        [[0.        +0.j, 0.        +0.j],
         [0.        +0.j, 0.        +0.j]]]])

# Reduced Density Matrix

In [8]:
kept= 0

In [9]:
_ = singlet_ketnode[1-kept] ^ singlet_branode[1-kept]
reddenmat = singlet_ketnode @ singlet_branode

In [10]:
reddenmat.tensor

array([[0.6+0.j, 0. +0.j],
       [0. +0.j, 0.4+0.j]])

In [11]:
pyqentangle.bipartite_reddenmat_nocheck.bipartitepurestate_reduceddensitymatrix_nocheck(singlet, kept)

array([[0.6+0.j, 0. +0.j],
       [0. +0.j, 0.4+0.j]])

# Partial Transpose

In [12]:
singlet_ketnode = tn.Node(singlet)
singlet_branode = tn.Node(np.conj(singlet))
final_node = tn.outer_product(singlet_ketnode, singlet_branode)

In [14]:
final_node.tensor

array([[[[0.        +0.j, 0.        +0.j],
         [0.        +0.j, 0.        +0.j]],

        [[0.        +0.j, 0.6       +0.j],
         [0.48989795+0.j, 0.        +0.j]]],


       [[[0.        +0.j, 0.48989795+0.j],
         [0.4       +0.j, 0.        +0.j]],

        [[0.        +0.j, 0.        +0.j],
         [0.        +0.j, 0.        +0.j]]]])

In [15]:
e0 = final_node[0]
e1 = final_node[1]
e2 = final_node[2]
e3 = final_node[3]
final_node.reorder_edges([e0, e3, e2, e1])

In [16]:
final_node.tensor

array([[[[0.        +0.j, 0.        +0.j],
         [0.        +0.j, 0.48989795+0.j]],

        [[0.        +0.j, 0.6       +0.j],
         [0.        +0.j, 0.        +0.j]]],


       [[[0.        +0.j, 0.        +0.j],
         [0.4       +0.j, 0.        +0.j]],

        [[0.48989795+0.j, 0.        +0.j],
         [0.        +0.j, 0.        +0.j]]]])