In [1]:
import numpy as np

In [2]:
import tensornetwork as tn

In [3]:
a = np.sqrt(np.array([[0.2, 0.1, 0.1], [0.3, 0.2, 0.1]]))

In [4]:
node_a = tn.Node(a)

In [5]:
u, s, vh, err = tn.split_node_full_svd(node_a, [node_a[0]], [node_a[1]])

In [7]:
u.tensor

array([[-0.63190507, -0.77504579],
       [-0.77504579,  0.63190507]])

In [8]:
s.tensor

array([[0.99827058, 0.        ],
       [0.        , 0.05878643]])

In [9]:
vh.tensor

array([[-0.7083316 , -0.5473836 , -0.44568771],
       [-0.00854539,  0.63799655, -0.7699918 ]])

In [10]:
u.tensor[:, 0]

array([-0.63190507, -0.77504579])

In [12]:
vh.tensor[0, :]

array([-0.7083316 , -0.5473836 , -0.44568771])