In [1]:
import numpy as np
import tensornetwork as tn
from math import sqrt

# Singlet Matrix

$\begin{equation} |\psi\rangle = \frac{1}{\sqrt{2}} \left( |00\rangle + |11\rangle   \right) \end{equation}$

In [2]:
singlet = np.array([[sqrt(0.5), 0], [0, sqrt(0.5)]])

# Density Matrix

$\rho = |\psi\rangle \langle \psi | = \sum_{i j i' j'} \psi_{ij} \psi^*_{i'j'} |ij\rangle \langle i'j'|$

In [3]:
singlet_ketnode = tn.Node(singlet)
singlet_branode = tn.Node(np.conj(singlet))

In [4]:
final_node = tn.outer_product(singlet_ketnode, singlet_branode)

In [5]:
final_node.tensor

array([[[[0.5, 0. ],
         [0. , 0.5]],

        [[0. , 0. ],
         [0. , 0. ]]],


       [[[0. , 0. ],
         [0. , 0. ]],

        [[0.5, 0. ],
         [0. , 0.5]]]])

# Partial Trace

$\text{Tr}_2 \rho = \sum_{ii'} \left(\sum_j \psi_{ij} \psi^*_{i'j} \right) |i\rangle \langle i|$

In [6]:
# integrate out second system
_ = singlet_ketnode[1] ^ singlet_branode[1]
reddenmat = singlet_ketnode @ singlet_branode

In [7]:
reddenmat.tensor

array([[0.5, 0. ],
       [0. , 0.5]])

# Partial Transpose

$\text{partial_transpose} \rho = \sum_{iji'j'} \psi_{ij} \psi^*_{i'j'} |ij'\rangle \langle i'j|$

In [8]:
e0 = final_node[0]
e1 = final_node[1]
e2 = final_node[2]
e3 = final_node[3]
final_node.reorder_edges([e0, e3, e2, e1])

In [9]:
final_node.tensor

array([[[[0.5, 0. ],
         [0. , 0. ]],

        [[0. , 0. ],
         [0.5, 0. ]]],


       [[[0. , 0.5],
         [0. , 0. ]],

        [[0. , 0. ],
         [0. , 0.5]]]])