In [1]:
import numpy as np
import tensorflow as tf

In [2]:
Y = tf.Variable(np.random.rand(5,2), dtype='float')
sqY = tf.reduce_sum(Y*Y, 1)
sqY = tf.reshape(sqY, [-1, 1])
sqDY = sqY - 2*tf.matmul(Y, tf.transpose(Y)) + tf.transpose(sqY)
DY = tf.sqrt(sqDY)

In [3]:
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

In [4]:
sess.run(Y)

array([[ 0.38740048,  0.44377303],
       [ 0.13173872,  0.66987783],
       [ 0.55111778,  0.59641796],
       [ 0.47506228,  0.5284853 ],
       [ 0.71277624,  0.28119344]], dtype=float32)

In [5]:
sess.run(sqDY)

array([[ 0.        ,  0.11648631,  0.05010384,  0.01486075,  0.13230151],
       [ 0.11648631,  0.        ,  0.18127513,  0.13786286,  0.48868012],
       [ 0.05010384,  0.18127513,  0.        ,  0.01039928,  0.12549996],
       [ 0.01486075,  0.13786286,  0.01039928,  0.        ,  0.11766112],
       [ 0.13230151,  0.48868012,  0.12549996,  0.11766112,  0.        ]], dtype=float32)

In [6]:
sess.run(DY)

array([[ 0.        ,  0.3413009 ,  0.22383888,  0.12190467,  0.36373276],
       [ 0.3413009 ,  0.        ,  0.42576411,  0.37129888,  0.69905657],
       [ 0.22383888,  0.42576411,  0.        ,  0.10197686,  0.35425973],
       [ 0.12190467,  0.37129888,  0.10197686,  0.        ,  0.34301767],
       [ 0.36373276,  0.69905657,  0.35425973,  0.34301767,  0.        ]], dtype=float32)

In [7]:
sess.run(tf.gradients(tf.reshape(sqDY, [-1]), Y))

[array([[-1.28437233, -1.20352936],
        [-6.3976078 ,  3.31856632],
        [ 1.98997402,  1.84936905],
        [ 0.46886349,  0.49071598],
        [ 5.22314262, -4.45512104]], dtype=float32)]

In [8]:
sess.run(tf.gradients(tf.reshape(tf.reduce_sum(tf.sqrt(sqDY+tf.diag(tf.ones(5)))), [-1]), Y))

[array([[-3.19194746, -3.18470192],
        [-6.97982597,  3.54366684],
        [ 4.01178932,  4.13074875],
        [ 0.40987587,  0.7377491 ],
        [ 5.75011158, -5.22746181]], dtype=float32)]

In [9]:
sess.run(tf.reshape(sqDY, [-1]))

array([ 0.        ,  0.11648631,  0.05010384,  0.01486075,  0.13230151,
        0.11648631,  0.        ,  0.18127513,  0.13786286,  0.48868012,
        0.05010384,  0.18127513,  0.        ,  0.01039928,  0.12549996,
        0.01486075,  0.13786286,  0.01039928,  0.        ,  0.11766112,
        0.13230151,  0.48868012,  0.12549996,  0.11766112,  0.        ], dtype=float32)

In [10]:
sess.run(tf.gradients(tf.reduce_sum([sqDY[i, j] for i in range(5) for j in range(i+1, 5)]), Y))

[array([[-0.64218581, -0.60176468],
        [-3.19880342,  1.65928316],
        [ 0.99498677,  0.92468452],
        [ 0.23443198,  0.24535799],
        [ 2.61157155, -2.22756052]], dtype=float32)]

In [11]:
sess.run(tf.gradients(tf.reduce_sum([tf.sqrt(sqDY[i, j]) for i in range(5) for j in range(i+1, 5)]), Y))

[array([[-1.59597421, -1.59235096],
        [-3.48991275,  1.7718339 ],
        [ 2.00589371,  2.06537437],
        [ 0.20493698,  0.3688736 ],
        [ 2.87505531, -2.61372995]], dtype=float32)]

In [12]:
sess.run(tf.gradients(tf.reduce_sum([DY[i, j] for i in range(5) for j in range(i+1, 5)]), Y))

[array([[ nan,  nan],
        [ nan,  nan],
        [ nan,  nan],
        [ nan,  nan],
        [ nan,  nan]], dtype=float32)]

In [13]:
sess.run([DY[i, j] for i in range(5) for j in range(i+1, 5)])

[0.3413009,
 0.22383888,
 0.12190467,
 0.36373276,
 0.42576411,
 0.37129888,
 0.69905657,
 0.10197686,
 0.35425973,
 0.34301767]

In [14]:
sess.run([tf.stack(DY[i, j]) for i in range(5) for j in range(i+1, 5)])

[0.3413009,
 0.22383888,
 0.12190467,
 0.36373276,
 0.42576411,
 0.37129888,
 0.69905657,
 0.10197686,
 0.35425973,
 0.34301767]

In [15]:
sess.close()