In [1]:
import numpy as np
import tensorflow as tf

In [2]:
M = tf.Variable(np.random.rand(10), dtype='float')
H = M*M+0.25*M*M*M*M

In [3]:
gradH = tf.gradients(H, M)[0]
hessH = tf.hessians(H, M)[0]

In [4]:
Delta = tf.divide(gradH, tf.diag_part(hessH))

In [5]:
laplH = tf.gradients(gradH, M)[0]

In [6]:
update = tf.assign(M, M-0.01*gradH/laplH)

In [7]:
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

In [8]:
sess.run(M)

array([ 0.33132228,  0.41505745,  0.03074855,  0.52123094,  0.63073641,
        0.81086659,  0.09089214,  0.72064352,  0.99729991,  0.44065094], dtype=float32)

In [9]:
sess.run(gradH)

array([ 0.69901532,  0.901618  ,  0.06152618,  1.18407071,  1.51239777,
        2.15488195,  0.18253519,  1.81553686,  2.98652124,  0.96686459], dtype=float32)

In [10]:
sess.run(hessH)

array([[ 2.32932377,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  2.51681805,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  2.00283647,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  2.81504536,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  3.1934855 ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         3.97251415,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  2.02478385,  0.        

In [11]:
sess.run(Delta)

array([ 0.30009368,  0.3582373 ,  0.03071952,  0.4206222 ,  0.47358847,
        0.54244792,  0.09015045,  0.51027161,  0.59924322,  0.37438807], dtype=float32)

In [12]:
sess.run(laplH)

array([ 2.32932377,  2.51681805,  2.00283647,  2.81504536,  3.1934855 ,
        3.97251415,  2.02478385,  3.55798149,  4.98382139,  2.58251977], dtype=float32)

In [13]:
for _ in range(100):
    sess.run(update)

In [14]:
sess.run(M)

array([ 0.1269903 ,  0.16300422,  0.01125964,  0.21222739,  0.26771143,
        0.37003854,  0.03339008,  0.3170661 ,  0.48958024,  0.17448449], dtype=float32)

In [15]:
sess.close()