In [1]:
import numpy as np
import pandas as pd
import torch
from torch.autograd import Variable
from torch.nn import Parameter
import torch.nn.functional as F

In [2]:
torch.cuda.is_available()

False

In [3]:
dataset1 = pd.read_csv('dataset1.csv')
x = np.array([dataset1['x1'], dataset1['x2']], dtype=np.float32).T
y = np.array([dataset1['y']], dtype=np.float32).T

In [4]:
class LinearRegression1(torch.nn.Module):
    def __init__(self):
        super(LinearRegression1, self).__init__()
        self.linearblock = torch.nn.Linear(2, 1)
        
    def forward(self, x):
        return self.linearblock(x)


class LinearRegression2(torch.nn.Module):
    def __init__(self):
        super(LinearRegression2, self).__init__()
        self.W = Parameter(torch.rand(2, 1), requires_grad=True)
        self.b = Parameter(torch.rand(1), requires_grad=True)
        
    def forward(self, x):
        return torch.mm(x, self.W) + self.b

In [6]:
lrModel1 = LinearRegression1()

optimizer = torch.optim.Adam(lrModel1.parameters())

for _ in range(1000):
    xtrain = torch.tensor(x)
    ytrain = torch.tensor(y)
    
    ypred = lrModel1(xtrain)
    loss = F.mse_loss(ypred, ytrain)
    
    optimizer.zero_grad()
    
    loss.backward()
    
    optimizer.step()

In [7]:
list(lrModel1.parameters())

[Parameter containing:
 tensor([[ 0.9539, -0.2332]], requires_grad=True), Parameter containing:
 tensor([0.8878], requires_grad=True)]

In [8]:
dataset2 = pd.read_csv('dataset2.csv')
x = np.array([dataset2['x1'], dataset2['x2']], dtype=np.float32).T
y = np.array([dataset2['y']], dtype=np.float32).T

In [9]:
lrModel2 = LinearRegression2()

optimizer = torch.optim.Adam(lrModel2.parameters())

for _ in range(1000):
    xtrain = torch.tensor(x)
    ytrain = torch.tensor(y)
    
    ypred = lrModel2(xtrain)
    loss = F.mse_loss(ypred, ytrain)
    
    optimizer.zero_grad()
    
    loss.backward()
    
    optimizer.step()

In [10]:
list(lrModel2.parameters())

[Parameter containing:
 tensor([[-0.5782],
         [ 0.6069]], requires_grad=True), Parameter containing:
 tensor([-0.5906], requires_grad=True)]

In [11]:
torch.save(lrModel1.state_dict(), 'torchModel1.pkl')
torch.save(lrModel2.state_dict(), 'torchModel2.pkl')

In [12]:
lrModel1(torch.tensor([2.3, 1.2]))

tensor([2.8019], grad_fn=<AddBackward0>)

In [13]:
lrModel2(torch.tensor([[2.3, 1.2]]))

tensor([[-1.1922]], grad_fn=<AddBackward0>)