In [4]:
import numpy as np
import torch
from torch.nn import Parameter

In [5]:
class LinearRegression1(torch.nn.Module):
    def __init__(self):
        super(LinearRegression1, self).__init__()
        self.linearblock = torch.nn.Linear(2, 1)
        
    def forward(self, x):
        return self.linearblock(x)


class LinearRegression2(torch.nn.Module):
    def __init__(self):
        super(LinearRegression2, self).__init__()
        self.W = Parameter(torch.rand(2, 1), requires_grad=True)
        self.b = Parameter(torch.rand(1), requires_grad=True)
        
    def forward(self, x):
        return torch.mm(x, self.W) + self.b

In [6]:
lrModel1 = LinearRegression1()
lrModel1.load_state_dict(torch.load('torchModel1.pkl'))

lrModel2 = LinearRegression2()
lrModel2.load_state_dict(torch.load('torchModel2.pkl'))

<All keys matched successfully>

In [8]:
list(lrModel1.parameters())

[Parameter containing:
 tensor([[ 0.9539, -0.2332]], requires_grad=True), Parameter containing:
 tensor([0.8878], requires_grad=True)]

In [9]:
list(lrModel2.parameters())

[Parameter containing:
 tensor([[-0.5782],
         [ 0.6069]], requires_grad=True), Parameter containing:
 tensor([-0.5906], requires_grad=True)]

In [10]:
lrModel1(torch.tensor([2.3, 1.2]))

tensor([2.8019], grad_fn=<AddBackward0>)

In [12]:
lrModel2(torch.tensor([[2.3, 1.2]]))

tensor([[-1.1922]], grad_fn=<AddBackward0>)