In [1]:
import numpy as np

In [2]:
import f90brownian

In [4]:
S = f90brownian.f90brownian.heston_price_simulation(np.log(100.), 0.01, 0.01, 0.01, 0.1, 0.0001, 0.2, 0.1, 1000, 1000)
S

(array([[  0.      , 100.176254, 100.765144, ..., 308.11688 , 308.1176  ,
         307.84933 ],
        [  0.      ,  99.688644, 100.138054, ..., 240.61798 , 240.9204  ,
         241.42006 ],
        [  0.      , 100.51373 , 100.80349 , ..., 283.8602  , 284.7795  ,
         285.1445  ],
        ...,
        [  0.      ,  99.91197 ,  99.56944 , ..., 253.03621 , 250.59105 ,
         250.92465 ],
        [  0.      ,  99.485916,  99.239494, ..., 283.9356  , 285.57678 ,
         285.08154 ],
        [  0.      , 100.15539 , 100.49063 , ..., 251.67477 , 251.60806 ,
         252.6915  ]], dtype=float32),
 array([[0.01      , 0.01000407, 0.01000387, ..., 0.01002289, 0.01002631,
         0.01003292],
        [0.01      , 0.00999556, 0.00999844, ..., 0.00998215, 0.00998287,
         0.00997812],
        [0.01      , 0.01000072, 0.00999651, ..., 0.00999455, 0.00999079,
         0.00999375],
        ...,
        [0.01      , 0.00999798, 0.00999419, ..., 0.00997193, 0.00996903,
         0.00996857

In [5]:
from finsim.simulation.stock import HestonStockPrices

In [8]:
heston_simulator = HestonStockPrices(100, 0.01, 0.01, 0.01, 0.1, 0.0001, 0.2)

In [19]:
PS = heston_simulator.generate_time_series(100, 0.1, nbsimulations=1000)
PS

(array([[100.        ,  99.90379968,  99.82814124, ..., 297.93339538,
         297.3756108 , 296.57074328],
        [100.        , 100.55763265, 100.65601456, ..., 310.49652484,
         312.6695471 , 314.1780856 ],
        [100.        ,  99.86193949, 100.31198757, ..., 263.63925545,
         264.4547573 , 265.2009569 ],
        ...,
        [100.        , 100.0129755 ,  99.5898413 , ..., 288.13457037,
         288.78326543, 288.72808524],
        [100.        , 100.46365992, 100.44736786, ..., 212.25410542,
         212.88388499, 214.37231288],
        [100.        , 100.17631864, 100.50815652, ..., 252.9594086 ,
         254.0583577 , 254.49931214]]),
 array([[0.01      , 0.00999959, 0.01000237, ..., 0.00996056, 0.00995908,
         0.00995579],
        [0.01      , 0.01000918, 0.01001008, ..., 0.01000354, 0.01000603,
         0.0100091 ],
        [0.01      , 0.01000216, 0.0100047 , ..., 0.01001074, 0.01001496,
         0.01001765],
        ...,
        [0.01      , 0.00999829, 0.0

In [26]:
S100 = [S[0][i][100] for i in range(1000)]
np.mean(S100, axis=0)

110.506516

In [27]:
PS100 = [PS[0][i][100] for i in range(1000)]
np.mean(PS100, axis=0)

110.38262156012404