In [1]:
import numpy as np

In [2]:
import f90brownian

In [3]:
S, v = f90brownian.f90brownian.heston_price_simulation(np.log(100.), 0.01, 0.01, 0.01, 0.1, 0.0001, 0.2, 0.1, 1000, 100000)
S

array([[100.00001 , 103.43281 , 101.85958 , ..., 202.83846 , 211.01207 ,
        205.49913 ],
       [100.00001 ,  94.25886 ,  95.38601 , ..., 178.32301 , 181.8494  ,
        185.06673 ],
       [100.00001 , 101.685265, 104.722824, ..., 123.99444 , 122.70381 ,
        121.6269  ],
       ...,
       [100.00001 ,  98.87216 , 104.786964, ..., 125.07371 , 128.06703 ,
        122.76041 ],
       [100.00001 ,  96.160446,  95.02868 , ..., 122.38529 , 120.80746 ,
        127.38114 ],
       [100.00001 , 103.20299 , 102.42793 , ..., 408.43427 , 390.14572 ,
        394.3973  ]], dtype=float32)

In [4]:
np.sum(np.isnan(S[:, 100]))

1

In [5]:
np.where(np.isnan(S[:, 100]))

(array([39253]),)

In [6]:
S[39253, :]

array([100.00001 , 103.97919 , 103.51466 , 107.8465  , 109.83596 ,
       104.99683 , 109.78475 , 111.55903 , 107.07251 , 103.59525 ,
        99.27618 , 101.68236 , 102.06486 ,  96.8629  ,  97.3866  ,
        91.098724,  89.70395 ,  85.95239 ,  82.57888 ,  84.47835 ,
        82.24666 ,  83.70479 ,  85.75801 ,  84.26737 ,  87.99128 ,
        88.73652 ,  87.487015,  87.886406,  92.18395 ,  92.24296 ,
        90.0404  ,  89.04611 ,  89.84492 ,  88.095985,  90.36902 ,
        90.40074 ,  90.57993 ,  95.03149 ,  93.34088 ,  95.29854 ,
       101.21743 ,  97.85031 , 100.90761 ,  99.054405, 103.189896,
       104.36714 , 104.657585, 106.28264 , 107.59014 , 110.5348  ,
       114.726204, 109.03563 , 107.123375, 105.32392 , 106.40155 ,
       108.75212 , 111.940186, 113.466194, 114.29849 , 108.39536 ,
       108.01669 , 104.55104 , 105.50181 , 103.57737 ,  98.80105 ,
       100.910835, 104.90355 , 104.10332 , 101.95575 , 102.46437 ,
       103.829216, 105.55324 , 107.93133 , 108.01958 , 103.813

In [7]:
v[39253, :]

array([0.01      , 0.00999889, 0.01000011, 0.00999994, 0.00999957,
       0.00999926, 0.01000423, 0.01000525, 0.01001061, 0.01001174,
       0.01000832, 0.01000916, 0.01000886, 0.01000538, 0.0100041 ,
       0.01000342, 0.0100011 , 0.01000301, 0.01000189, 0.01000337,
       0.00999874, 0.00999229, 0.00999337, 0.00999131, 0.00999013,
       0.00999048, 0.00998513, 0.00998057, 0.00997907, 0.00997844,
       0.00997831, 0.00997574, 0.00997996, 0.00998096, 0.009979  ,
       0.00997789, 0.00998055, 0.00997806, 0.0099725 , 0.00997219,
       0.00997151, 0.00997476, 0.0099747 , 0.00997238, 0.00996948,
       0.00996946, 0.0099682 , 0.0099675 , 0.00996301, 0.00996276,
       0.00996758, 0.00996443, 0.00996389, 0.00996029, 0.00995979,
       0.00996038, 0.00995998, 0.00996194, 0.0099649 , 0.00996594,
       0.009967  , 0.00996604, 0.00996848, 0.00997388, 0.00997469,
       0.00997344, 0.00997333, 0.00997003, 0.00997363, 0.00997323,
       0.00996679, 0.0099703 , 0.00997713, 0.00998519, 0.00997

In [8]:
from finsim.simulation.stock import HestonStockPrices

In [9]:
heston_simulator = HestonStockPrices(100, 0.01, 0.01, 0.01, 0.1, 0.0001, 0.2)

In [12]:
PS, Pv = heston_simulator.generate_time_series(100, 0.1, nbsimulations=100000)
PS

array([[  0.        ,  99.89205933,  99.94556427, ..., 233.66722107,
        234.82752991, 235.05999756],
       [  0.        , 100.45010376,  99.79998016, ..., 281.42337036,
        279.86834717, 279.54516602],
       [  0.        , 100.10434723, 100.25997925, ..., 290.65106201,
        290.05697632, 291.32580566],
       ...,
       [  0.        ,  99.91859436,  99.80055237, ..., 301.15222168,
        300.41674805, 301.4503479 ],
       [  0.        ,  99.66487885,  99.65570068, ..., 246.49961853,
        245.73257446, 246.28507996],
       [  0.        , 100.19952393, 100.50453186, ..., 305.42755127,
        305.6383667 , 305.57058716]])

In [13]:
np.mean(PS[:, 100])

nan

In [14]:
np.where(np.isnan(PS[:, 100]))

(array([98750]),)

In [15]:
PS[98750, :]

array([  0.        , 100.42203522, 100.19741821, 100.27700043,
       100.45077515, 100.46360779, 100.77927399, 100.80916595,
       100.9087677 , 101.10407257, 101.23596191, 101.54702759,
       101.71411896, 101.50466919, 100.54987335, 101.05620575,
       101.64343262, 101.79763031, 101.83054352, 102.21720123,
       101.84564209, 101.88047028, 102.3684082 , 102.52590942,
       102.44116974, 102.48748779, 102.60352325, 102.04130554,
       101.95550537, 102.25030518, 102.91181946, 103.94107056,
       104.41348267, 104.68702698, 104.86604309, 105.21800995,
                nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan,          nan,          nan,       

In [16]:
Pv[98750, :]

array([0.01      , 0.00999537, 0.00999394, 0.00998956, 0.00998837,
       0.0099863 , 0.00998545, 0.00997714, 0.00997389, 0.00997206,
       0.00997521, 0.00998112, 0.00998198, 0.00998312, 0.00998142,
       0.00997996, 0.00997684, 0.00997793, 0.00998241, 0.00998354,
       0.00998468, 0.00998758, 0.00998389, 0.00998899, 0.00999343,
       0.00999322, 0.00998856, 0.00998812, 0.00998473, 0.00998856,
       0.00998762, 0.00999633, 0.009993  , 0.00998922, 0.00998737,
       0.00998945,        inf,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        