In [1]:
import numpy as np

In [2]:
import f90brownian

In [3]:
f90brownian.f90brownian.symmatd2eigen(np.array([[0., 2.], [2., 0.]]))

(array([ 2., -2.], dtype=float32),
 array([[ 0.70710677,  0.70710677],
        [ 0.70710677, -0.70710677]], dtype=float32))

In [4]:
rho = np.array([[1.5, -1.75], [-1.75, 2.5]])
z = np.array([f90brownian.f90brownian.normal2ddistsampling(rho) for _ in range(100000)])

In [5]:
np.mean(z, axis=0)

array([ 0.00373441, -0.00509215], dtype=float32)

In [6]:
np.cov(z.T)

array([[ 1.50693226, -1.76006904],
       [-1.76006904,  2.5139958 ]])

In [7]:
variances, X = f90brownian.f90brownian.symmatd2eigen(rho)
f90brownian.f90brownian.symmatd2eigen(rho)

(array([3.8200274 , 0.17997253], dtype=float32),
 array([[-0.60219556, -0.79834867],
        [ 0.79834867, -0.6021955 ]], dtype=float32))

In [8]:
lamb, evec = np.linalg.eig(rho)
np.linalg.eig(rho)

(array([0.17997253, 3.82002747]),
 array([[-0.79834865,  0.60219551],
        [-0.60219551, -0.79834865]]))

In [9]:
z1 = np.array([[f90brownian.f90brownian.normaldistsampling(), f90brownian.f90brownian.normaldistsampling()] for _ in range(100000)])
z1 = z1.T

In [17]:
# z = X @ np.diag(np.sqrt(variances)) @ z1
z = evec @ np.diag(np.sqrt(lamb)) @ z1

In [18]:
z

array([[-1.36479782, -1.18989342, -0.09586901, ...,  1.11627111,
        -1.36600405, -1.80951177],
       [ 2.4349731 ,  0.79027647,  0.63790499, ..., -0.81062036,
         0.66845951,  3.27207303]])

In [19]:
z1

array([[-0.88806516,  1.11742914, -0.7250911 , ..., -0.9500035 ,
         1.62176514, -1.23943222],
       [-1.41511798, -0.6894204 , -0.29010266, ...,  0.67504656,
        -0.69392318, -1.89406788]])

In [20]:
np.cov(z)

array([[ 1.50014283, -1.75012355],
       [-1.75012355,  2.49714037]])

In [21]:
np.cov(z1)

array([[ 0.99408365, -0.00178182],
       [-0.00178182,  0.99956754]])

In [15]:
np.cov(np.array([[1, -2], [-1, 2]]))

array([[ 4.5, -4.5],
       [-4.5,  4.5]])